"""Definitions and server resources (port of ``sc3/synth``).

The definition layer — both def formats, FaustDefs and UGen-graph SynthDefs —
and the server resources:

- `signals` — lowercase callables mapping Faust's Signal
  API; compose them (operators or functions) into the JSON signal tree.
- `boxes` — the same pattern over Faust's Box API: point-free composition
  plus the `boxes.faust` escape hatch that turns any Faust expression
  (the stdlib included) into a composable `Box`.
- `faustdef` — `FaustDef`: build the ``/def_send faust``
  payload (signal tree, source, or box tree) and list its controls.
- `node` / `bus` /
  `buffer` — `Synth`/`Group`/`Bus`/
  `Buffer` and their client-side allocators.
- `server` — `Server`: the live OSC round-trip
  (definitions, nodes, buses, buffers, ``/done``/``/fail``, ``/server_notify``).
- `ugens` / `synthdef` — the UGen
  graph (lowercase callables → `Ugen`/`Control`) and
  `SynthDef` (``/def_send synth``), the UGen-graph counterpart of the Faust
  `signals` / `FaustDef` pair.
"""

from . import boxes
from . import signals
from . import ugens
from .asdef import as_def, expr_channels
from .boxes import Box
from .bus import AudioBusAllocator, Bus, ControlBusAllocator
from .clocksync import SampleClockModel, UdpSampleClock
from .buffer import Buffer, BufferAllocator
from .expr import Expr, FaustExpr, SynthExpr
from .faustdef import FaustDef
from .graphdef import GraphDef
from .patch import DefPatch, GraphPatch, synthdef_ports
from .node import AddAction, Group, Node, NodeIdAllocator, ROOT_NODE_ID, Synth
from .info import (
    BufferInfo,
    ControlInfo,
    DefInfo,
    NodeInfo,
    NodeMap,
    Tree,
    UgenInfo,
    UgenInput,
)
from .server import Server, ServerInfo, ServerOptions
from .signals import Signal
from .synthdef import SynthDef
from . import pv_expr
from .ugens import (
    ChannelList,
    Control,
    DoneAction,
    Env,
    Ugen,
    buf_channels,
    buf_dur,
    buf_rate_scale,
    buf_rd,
    buf_sample_rate,
    chans,
    control,
    dbrown,
    dbufrd,
    demand,
    dgeom,
    dibrown,
    disk_in,
    disk_out,
    diwhite,
    drand,
    dseq,
    dseries,
    dshuf,
    dstutter,
    dswitch1,
    dup,
    duty,
    dwhite,
    dxrand,
    env_gen,
    fft,
    ifft,
    impulse,
    in_,
    in_ctl,
    lag,
    local_in,
    local_out,
    madd,
    mix,
    osc,
    oscn,
    out,
    out_ctl,
    play_buf,
    poll,
    conv,
    partconv_frames,
    pv_add,
    pv_kernel,
    pv_bin_shift,
    pv_brick_wall,
    pv_copy_phase,
    pv_mag_above,
    pv_mag_below,
    pv_mag_clip,
    pv_mag_freeze,
    pv_mag_mul,
    pv_mag_shift,
    pv_mag_smear,
    pv_max,
    pv_min,
    pv_mul,
    rand,
    replace_out,
    sample_rate,
    send_reply,
    send_trig,
    shaper,
    sine,
    sum3,
    sum4,
    tduty,
    var_lag,
    vosc,
    white_noise,
)

__all__ = [
    "boxes",
    "signals",
    "ugens",
    "as_def",
    "expr_channels",
    "Expr",
    "SynthExpr",
    "FaustExpr",
    "Box",
    "Signal",
    "FaustDef",
    "SynthDef",
    "GraphDef",
    "GraphPatch",
    "DefPatch",
    "synthdef_ports",
    "Node",
    "Ugen",
    "Control",
    "ChannelList",
    "control",
    "chans",
    "dup",
    "mix",
    "sine",
    "impulse",
    "white_noise",
    "in_",
    "in_ctl",
    "out",
    "out_ctl",
    "replace_out",
    "send_trig",
    "send_reply",
    "poll",
    "fft",
    "ifft",
    "pv_mag_above",
    "pv_mag_below",
    "pv_mag_clip",
    "pv_brick_wall",
    "pv_add",
    "pv_mul",
    "pv_min",
    "pv_max",
    "pv_mag_mul",
    "pv_copy_phase",
    "pv_mag_freeze",
    "pv_mag_smear",
    "pv_bin_shift",
    "pv_mag_shift",
    "pv_kernel",
    "pv_expr",
    "conv",
    "partconv_frames",
    "play_buf",
    "buf_rd",
    "buf_sample_rate",
    "buf_rate_scale",
    "buf_channels",
    "buf_dur",
    "osc",
    "oscn",
    "vosc",
    "shaper",
    "disk_in",
    "disk_out",
    "local_in",
    "local_out",
    "madd",
    "sum3",
    "sum4",
    "lag",
    "var_lag",
    "sample_rate",
    "rand",
    "dseq",
    "drand",
    "dxrand",
    "dshuf",
    "dseries",
    "dgeom",
    "dwhite",
    "diwhite",
    "dbrown",
    "dibrown",
    "dstutter",
    "dswitch1",
    "dbufrd",
    "demand",
    "duty",
    "tduty",
    "env_gen",
    "Env",
    "DoneAction",
    "Bus",
    "AudioBusAllocator",
    "ControlBusAllocator",
    "Buffer",
    "BufferAllocator",
    "AddAction",
    "Group",
    "Synth",
    "NodeIdAllocator",
    "ROOT_NODE_ID",
    "Server",
    "ServerOptions",
    "ServerInfo",
    "DefInfo",
    "ControlInfo",
    "BufferInfo",
    "NodeInfo",
    "NodeMap",
    "Tree",
    "UgenInfo",
    "UgenInput",
    "UdpSampleClock",
    "SampleClockModel",
]
