"""Ephemeral defs: turning a bare expression into a sendable def.

The ambient verbs (`clausters.play`, `clausters.plot`, `clausters.render`)
accept a bare expression — a `Ugen` graph, a `ChannelList`, a Faust `Signal` or
a `Box` — where a def is needed; `as_def` is the one coercion they share, so
what is coercible is decided here and nowhere else. A `Ugen` expression is
wrapped in ``out(0.0, expr)`` unless it already is a **sink** (see
`_SINK_KINDS`); a `ChannelList` lays its non-sink members on consecutive buses;
a Faust expression needs no wrapping — its outputs map to buses on their own.
Names are autogenerated unless given, so each coercion is its own def — see
`_tmp_name` for what the generated name has to guarantee.

`expr_channels` answers the other half: how many buses the coercion would lay.
The verbs read it differently on purpose — see its docstring.
"""

import uuid

from .boxes import Box
from .faustdef import FaustDef
from .graphdef import GraphDef
from .signals import Signal
from .synthdef import SynthDef
from .ugens import ChannelList, Ugen, out

#: UGen kinds that **deliver data out of the graph**: audio or control to a
#: bus, audio to a file, OSC or console text to a client. An expression rooted
#: in one of these is already where it is going, so `as_def` does not wrap it.
#:
#: The criterion is delivery, *not* "has a side effect". `FreeSelf`,
#: `PauseSelf`, `FreeSelfWhenDone` and `Done` manage the enclosing synth or the
#: graph and pass their input through, so wrapping them is exactly right —
#: ``out(0, free_self_when_done(env * sig))`` is the idiom. `DetectSilence`
#: writes 0/1 for the rest of the graph and takes a done action; both are
#: inward, so it is not a sink either. `DiskOut` *is* one: it delivers audio to
#: a file. It also passes its input through, but the criterion is applied
#: without an exception, so ``play(disk_out(p, sig))`` records without
#: sounding and recording *and* hearing is the explicit
#: ``out(0, disk_out(p, sig))``.
_SINK_KINDS = {
    "Out", "ReplaceOut", "OutCtl", "LocalOut", "DiskOut",
    "SendTrig", "SendReply", "Poll",
}

#: Prefix marking a def as **ephemeral** — the server keeps it in memory and
#: never writes it to its persistent store (`docs/schemas.md`, "Def names").
#: The def family is part of it so two coercions of different families can
#: never land on the same name.
_TMP_PREFIX = "tmp_"


def _tmp_name(family: str) -> str:
    """A name for a def nobody named: ``tmp_<family>_<id>``.

    Three properties, each of which was missing from the ``_expr_<n>`` counter
    this replaces, and any two of whose absence collide:

    - **Unique across processes and runs.** A per-process counter restarts at 0
      every run, so a second session reuses the names of the first — and since
      the server persists what it receives, the old def is still sitting there
      under that name.
    - **Distinct per family.** One counter numbering both families let a
      SynthDef and a FaustDef claim the same name; the server resolves a name
      against one table before the other, so the wrong def answers.
    - **Marked ephemeral**, so the server never persists it at all: a name
      generated for one expression has no meaning to a later session, and a
      store that outlives the process should not accumulate them.
    """
    return f"{_TMP_PREFIX}{family}_{uuid.uuid4().hex[:12]}"


def _is_sink(m) -> bool:
    """Whether ``m`` already delivers its data somewhere — see `_SINK_KINDS`."""
    return isinstance(m, Ugen) and m.kind in _SINK_KINDS


def as_def(expr, name: str | None = None):
    """Coerce ``expr`` into a def, autonaming it unless ``name`` is given.

    A `SynthDef`/`FaustDef`/`GraphDef` passes through unchanged (``name`` is
    ignored); anything else is named ``tmp_<family>_<id>`` unless ``name`` says
    otherwise, which is what keeps the coercion's defs from colliding with each
    other or outliving the process (see `_tmp_name`). A `Ugen` becomes a
    `SynthDef` — wrapped in ``out(0.0, expr)``
    unless it already is a sink (`_SINK_KINDS`). A `ChannelList` becomes a
    multichannel `SynthDef`: a member that is a sink already knows where its
    data goes and passes through as a root, and the members that are not are
    the channels, laid on consecutive buses from 0 — so ``play(dup(expr))`` is
    stereo, and a reporter in the list does not push the audio off bus 0. A
    `Signal` becomes a one-output `FaustDef`, a `Box` a `FaustDef` with the
    box's own arity. Anything else raises `TypeError`.
    """
    if isinstance(expr, (SynthDef, FaustDef, GraphDef)):
        return expr
    if isinstance(expr, Ugen):
        name = name or _tmp_name("synthdef")
        return SynthDef(name, expr if _is_sink(expr) else out(0.0, expr))
    if isinstance(expr, ChannelList):
        name = name or _tmp_name("synthdef")
        roots, channel = [], 0
        for m in expr:
            if _is_sink(m):
                roots.append(m)
            else:
                roots.append(out(float(channel), m))
                channel += 1
        return SynthDef(name, *roots)
    if isinstance(expr, Signal):
        return FaustDef.from_signals(name or _tmp_name("faustdef"), expr)
    if isinstance(expr, Box):
        return FaustDef.from_box(name or _tmp_name("faustdef"), expr)
    raise TypeError(
        f"cannot make a def out of {type(expr).__name__}; expected a Ugen, a "
        "ChannelList, a Signal, a Box, or a def (SynthDef/FaustDef/GraphDef). "
        "A Control is a graph leaf, not an expression to play on its own: use "
        "it inside one."
    )


def expr_channels(expr) -> "int | None":
    """How many buses `as_def` would lay ``expr`` on, or ``None`` when that is
    not knowable (an already-built def routes its own roots, possibly to
    computed buses).

    The verbs read this differently, and the difference is deliberate.
    `clausters.plot` and `clausters.play` are conveniences, free to infer what
    was meant: plot **configures** its render from this, so a stereo pair plots
    as two channels. `clausters.render` is part of the NRT interface — its
    ``channels`` is the render's *output* count, a fact about the server being
    configured, not about the graph — so it derives nothing and only
    **checks**: an expression laid past the outputs is writing onto internal
    buses that reach no file.

    A sink lays no bus of `as_def`'s choosing, so an expression made only of
    sinks answers ``0`` — it routes itself, and there is nothing here to infer.
    """
    if isinstance(expr, ChannelList):
        return sum(1 for m in expr if not _is_sink(m))
    if isinstance(expr, Ugen):
        return 0 if _is_sink(expr) else 1
    if isinstance(expr, Box):
        return expr.num_outputs
    if isinstance(expr, Signal):
        return 1
    return None
