"""Ephemeral defs: turning a bare expression into a sendable def.

The ambient verbs (`clausters.play`, `clausters.plot`) accept a bare
expression — a `Ugen` graph, a Faust `Signal` or a `Box` — where a def is
needed; `as_def` is the one coercion they share. A `Ugen` expression is
wrapped in ``out(0.0, expr)`` unless its root already is an output or a
side-effect UGen (a valid `SynthDef` root); a Faust expression needs no
wrapping — its outputs map to buses on their own. Names are autogenerated
(``_expr_<n>``) unless given, so each coercion is its own def.
"""

import itertools

from .boxes import Box
from .faustdef import FaustDef
from .graphdef import GraphDef
from .signals import Signal
from .synthdef import SynthDef
from .ugens import ChannelList, Ugen, out

#: UGen kinds that already are valid SynthDef roots (outputs and
#: side-effect UGens) — an expression rooted in one is not re-wrapped.
_ROOT_KINDS = {
    "Out", "ReplaceOut", "OutCtl", "LocalOut",
    "SendTrig", "SendReply", "Poll",
}

_names = itertools.count()


def as_def(expr, name: str | None = None):
    """Coerce ``expr`` into a def, autonaming it unless ``name`` is given.

    A `SynthDef`/`FaustDef`/`GraphDef` passes through unchanged (``name`` is
    ignored). A `Ugen` becomes a `SynthDef` — wrapped in ``out(0.0, expr)``
    when it is not already an output or side-effect root. A `ChannelList`
    becomes a multichannel `SynthDef`: its channels land on buses 0, 1, …
    (so ``play(dup(expr))`` is stereo). A `Signal` becomes a one-output
    `FaustDef`, a `Box` a `FaustDef` with the box's own arity. Anything else
    raises `TypeError`.
    """
    if isinstance(expr, (SynthDef, FaustDef, GraphDef)):
        return expr
    if name is None:
        name = f"_expr_{next(_names)}"
    if isinstance(expr, Ugen):
        root = expr if expr.kind in _ROOT_KINDS else out(0.0, expr)
        return SynthDef(name, root)
    if isinstance(expr, ChannelList):
        if all(isinstance(m, Ugen) and m.kind in _ROOT_KINDS for m in expr):
            return SynthDef(name, *expr)
        return SynthDef(name, out(0.0, expr))
    if isinstance(expr, Signal):
        return FaustDef.from_signals(name, expr)
    if isinstance(expr, Box):
        return FaustDef.from_box(name, expr)
    raise TypeError(
        f"cannot make a def out of {type(expr).__name__}; expected a Ugen, "
        "a ChannelList, a Signal, a Box, or a def (SynthDef/FaustDef/GraphDef)"
    )
