// Booting a standalone bundle against the page singletons.
//
// The engine↔host legs are already wired by the singletons (`gui/host.ts`),
// so this module only fetches the bundle's persisted files, loads its
// samples, replays the boot packets and opens the GuiDef. The bundle format —
// the native `--standalone` data directory plus the generated `bundle.json`
// manifest — is documented in docs/clients.md ("A standalone bundle in a
// tab").

import { bundle_boot_packets } from "./gui-host/clausters_gui.js";
import { loadOsc, decodePacket } from "./base/osc.ts";
import { server } from "./engine/server.ts";
import { guiHost } from "./gui/host.ts";

/// The manifest at a served bundle's root (`bundle.json`, generated by
/// `tools/bundle-manifest.py`).
export interface BundleManifest {
    gui: string;
    synthdefs?: string[];
    graphdefs?: string[];
    /// Whether the bundle carries a `boot.json` preset. Declared here so the
    /// boot never probes for the optional file (a probe's 404 would litter
    /// the console); absent means none. The generator sets it by looking.
    boot?: boolean;
    /// Server buffer index -> audio URL relative to the bundle.
    buffers?: Record<string, string>;
}

/// The persisted GuiDef record: `{ "id": <i32>, "gui": <tree> }`.
interface GuiDefRecord {
    id: number;
    gui: unknown;
}

// Each boot gets its own /sync ids so two bundles on one page cannot
// mistake each other's /synced for their own.
let nextSync = 0xb40;

async function fetchBytes(url: string): Promise<Uint8Array> {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
    return new Uint8Array(await response.arrayBuffer());
}

function interleave(audioBuffer: AudioBuffer): Float32Array {
    const channels = audioBuffer.numberOfChannels;
    const frames = audioBuffer.length;
    const out = new Float32Array(frames * channels);
    for (let ch = 0; ch < channels; ch++) {
        const data = audioBuffer.getChannelData(ch);
        for (let f = 0; f < frames; f++) out[f * channels + ch] = data[f];
    }
    return out;
}

/// Boots the bundle at `base` (a URL prefix) against the page singletons,
/// resolving to `{ id, tree }` once the engine confirmed the boot (/synced)
/// and the GuiDef opened. `name` overrides the manifest's GuiDef.
export async function bootBundle({
    base,
    name = null,
}: {
    base: string;
    name?: string | null;
}): Promise<{ id: number; tree: unknown }> {
    const engine = await server();
    const gui = await guiHost();
    await loadOsc();

    const manifest = (await (
        await fetch(`${base}/bundle.json`)
    ).json()) as BundleManifest;
    const guiName = name ?? manifest.gui;
    const [synthdefs, graphdefs, record] = await Promise.all([
        Promise.all((manifest.synthdefs ?? []).map(
            (n) => fetchBytes(`${base}/defs/synthdefs/${n}.json`))),
        Promise.all((manifest.graphdefs ?? []).map(
            (n) => fetchBytes(`${base}/defs/graphdefs/${n}.json`))),
        (async () =>
            (await (
                await fetch(`${base}/defs/guidefs/${guiName}.json`)
            ).json()) as GuiDefRecord)(),
    ]);
    // boot.json is optional — an absent preset is empty, as natively. The
    // manifest declares it, so an unlisted preset is never probed for (no
    // stray 404 in the console); a declared-but-missing one is a real error.
    let bootJson: string | null = null;
    if (manifest.boot) {
        const bootResponse = await fetch(`${base}/boot.json`);
        if (!bootResponse.ok) {
            throw new Error(
                `${base}/boot.json: HTTP ${bootResponse.status} ` +
                    "(declared by the manifest but not served)",
            );
        }
        bootJson = await bootResponse.text();
    }

    // Samples first, so a boot /s_new can already play them.
    for (const [index, url] of Object.entries(manifest.buffers ?? {})) {
        const bytes = await fetchBytes(`${base}/${url}`);
        const decoded = await engine.context.decodeAudioData(
            bytes.buffer as ArrayBuffer,
        );
        await engine.bLoad(
            Number(index), decoded.numberOfChannels, decoded.sampleRate,
            interleave(decoded),
        );
    }

    const syncId = (nextSync += 2);
    let bootedResolve!: () => void;
    const booted = new Promise<void>((r) => { bootedResolve = r; });
    const watch = (bytes: Uint8Array) => {
        for (const { addr, args } of decodePacket(bytes)) {
            if (addr === "/synced" && args[0] === syncId + 1) bootedResolve();
        }
    };
    engine.addReply(watch);
    try {
        const tree = JSON.stringify(record.gui);
        for (const packet of bundle_boot_packets(
            synthdefs, graphdefs, bootJson, tree, syncId,
        )) {
            engine.send(packet);
        }
        await Promise.race([booted, new Promise((_, reject) =>
            setTimeout(() => reject(
                new Error("bundle boot: no /synced from the engine")), 15000),
        )]);
        gui.bridge.def(record.id, tree);
        return { id: record.id, tree: record.gui };
    } finally {
        engine.removeReply(watch);
    }
}
