#!/usr/bin/env python3
"""Editing a buffer from the client: read the samples, change them, write them back.

A buffer is the one thing a piece keeps with **random access** — so unlike a
stream of events it can be read backwards, sliced and edited in place. What was
missing until now was the last step: samples came *out* of a buffer
(`Buffer.get_samples`) and could only get *in* by asking the server to fill one.
`Buffer.set_samples` closes that cycle, which is what an audio-editor view is
made of.

The point of interest is that whole round trip, done three times on one buffer,
each edit audible against the one before:

- **Read.** A ``sine1`` table is generated by the server (`Buffer.gen`) and
  pulled to the client — one round trip on a stream carrier, chunked on UDP.
- **Edit, then write.** The samples are reversed in Python and written back with
  `Buffer.set_samples`. A symmetric waveform survives that unchanged, so the
  second edit is the one that speaks: a fade carved into the table, which turns
  a steady tone into one that swells and dies inside every period — audibly
  buzzier, since a discontinuity is harmonics.
- **A single sample.** `Buffer.set_sample` pokes one value by flat index, the
  touch-up form.
- **What a write refuses.** Writing past the end raises `CommandError` instead
  of being clamped the way a *read* past the end is: a short read hands back
  less than you asked for and says so, a short write would drop samples you
  believe you stored.
- **The edits the server does for you.** Everything above pulls samples to the
  client and pushes them back. `Buffer.gain`, `Buffer.fade`, `Buffer.silence`
  and `Buffer.reverse` say what the edit *is* and no samples cross the wire at
  all — which is the difference between editing a table and editing a
  five-minute take. Their span is in **frames**, not flat indices, because a
  selection is a stretch of time across every channel.

Each version plays for a bar through `play_buf` before the next edit, so the
three are heard in a row. Indices are flat across channels, so a stereo buffer
is written interleaved ``L R L R ...`` — this one is mono, which keeps the
arithmetic in the example about editing rather than about de-interleaving.

This file is organized as ``# %%`` cells (the VS Code / Jupyter convention) and
**runs out of the box**. Install once, from the repo root::

    python -m venv .venv
    .venv/bin/pip install -e ./clients/python      # bundles the server binary

Run it cell by cell (Shift+Enter), or as a plain script --
``python clients/python/examples/buffers/buffer_edit.py``. It boots its own audio server
(`Session.live`), so run it with none already up on 57110. Needs an audio
output; listen to it, since the edits are the test.
"""

# %%
import sys
import time

from clausters import Session
from clausters.base import Routine
from clausters.defs import Buffer, Synth, SynthDef, control, out
from clausters.defs.ugens import buf_rd, phasor
from clausters.errors import CommandError

#: Frames in the table. Small enough to print, big enough to hear as a pitch
#: when scanned at audio rate.
FRAMES = 512

session = Session.live().activate()
server = session.server

# %% [markdown]
# ## A def that scans the buffer
#
# `buf_rd` reads at an index we compute, so a `phasor` sweeping 0..FRAMES turns
# the table into an oscillator at whatever rate we drive it. That is what makes
# an *edit* to the samples audible: the def never changes, only the data does.

# %%
scan = SynthDef(
    "table_scan",
    out(
        0.0,
        buf_rd(
            control("bufnum", 0.0, "ir"),
            0.0,
            phasor(0.0, control("freq", 440.0) * FRAMES / 48000.0, 0.0, FRAMES),
            1.0,
        )
        * control("amp", 0.2),
    ),
)
scan.send(server)

# %% [markdown]
# ## Fill it, then read it back
#
# The server computes the table (`gen`); the client pulls it (`get_samples`).

# %%
buf = Buffer.alloc(FRAMES, 1, server=server)
buf.gen("sine1", 5, 1.0)               # 5 = normalize | clear; no wavetable flag:
                                       # plain samples, which is what buf_rd reads

samples = list(buf.get_samples())
print(f"read {len(samples)} samples | peak {max(abs(s) for s in samples):.3f}")

# %% [markdown]
# ## Edit and write back
#
# Two edits, each written with one `set_samples`. Reversing a symmetric period
# is deliberately inaudible — it proves the write landed without changing what
# you hear — and the fade that follows is what you actually listen for.

# %%
reversed_table = samples[::-1]

# A fade carved into the period: the discontinuity at the wrap is harmonics.
faded = [s * (1.0 - i / len(samples)) for i, s in enumerate(samples)]


# %% [markdown]
# ## Hear the three versions in a row
#
# A routine yields beats on the session's clock — never a `time.sleep`, which
# would freeze the very thread the timeline runs on.

# %%
def sequence():
    voice = Synth("table_scan", {"bufnum": buf.bufnum, "freq": 440.0}, server=server)
    yield 1.5                                        # the original table

    buf.set_samples(reversed_table)                  # inaudible, and that is the point
    yield 1.5

    buf.set_samples(faded)                           # buzzier: a fade inside the period
    yield 1.5

    buf.set_sample(0, 0.0)                           # one sample, by flat index
    yield 1.0

    voice.free()
    yield 0.5


# %% [markdown]
# ## What a write refuses
#
# A read past the end returns what the buffer holds. A write past the end does
# not, because dropping samples silently would be data loss reported as success.

# %%
def show_the_refusal():
    tail = buf.get_samples(FRAMES - 4, 100)
    print(f"a read past the end returned {len(tail)} samples, not 100")
    try:
        buf.set_samples([0.0] * 100, start=FRAMES - 4)
    except CommandError as e:
        print(f"a write past the end was refused: {e}")
    else:
        print("!! the write should have been refused")


# %% [markdown]
# ## Saying what the edit is, instead of moving the samples
#
# The verbs above are the client's: read, change in Python, write back. These
# are the server's — the same edits named rather than performed here, so a
# five-minute take costs a message instead of a round trip of itself.
#
# The span is in **frames**: `start` and `frames` count time across every
# channel, unlike `set_samples`' flat interleaved index. And they **compose in
# flight** — fired with `wait=False` they chain on the server, each building on
# the last, so the three below are one pass over the table and not three
# read-modify-writes.

# %%
def edited_by_the_server():
    """Fade the table in, reverse it, then halve it — heard one after another."""
    voice = Synth("table_scan", {"bufnum": buf.bufnum, "freq": 440.0}, server=server)
    yield 1.5                                        # whatever the table holds now

    # `wait=False` because a routine must never block the clock thread on a
    # reply -- and because these chain on the server, each building on the last.
    print("fade in")
    buf.fade(wait=False)
    yield 1.5

    print("reversed, so the fade now dies instead")
    buf.reverse(wait=False)
    yield 1.5

    print("first quarter silenced, on exact zeros")
    buf.silence(0, FRAMES // 4, wait=False)
    yield 1.5

    print("and halved, all of it")
    buf.gain(0.5, wait=False)
    yield 1.5

    voice.free()
    yield 0.5


# %%
def run():
    """Play the three versions, show what a write refuses, then the server's own edits."""
    # The clock has to be running for a routine to fire: playing one on a
    # stopped clock queues it forever, silently.
    session.start()
    Routine(sequence).play()
    # The main thread waits while the clock thread plays -- never inside a
    # routine, which runs *on* that thread.
    time.sleep(6.5)
    show_the_refusal()
    Routine(edited_by_the_server).play()
    time.sleep(8.0)
    # Proof the server's own edits landed, read back once the routine is done
    # (a read is a round trip, so it belongs here and not inside the routine).
    after = buf.get_samples()
    head = max(abs(x) for x in after[: FRAMES // 4])
    peak = max(abs(x) for x in after)
    print(f"after the server's edits: peak {peak:.3f}, silenced quarter {head:.3f}")
    buf.free()


# %%
if __name__ == "__main__" and not hasattr(sys, "ps1"):
    try:
        run()
    finally:
        session.close()
else:
    print("up - run() to hear the edits, session.close() to end")
