//! Native side of the wasm parity harness: emits `score.bin` (the binary
//! score) and `native.f32` (the native render of that exact byte stream)
//! into `clients/web/tests/`, for the web package's `tests/parity.html` to
//! render through the wasm build and compare sample by sample. Run:
//! `cargo run -p clausters-web --example gen_parity`.
//!
//! **Two scenes, and the second is a different question.** The first is a
//! UGen-graph score: the same Rust DSP compiled twice, so the only thing
//! between the two renders is the libm each target links. The second sends a
//! **FaustDef**, where the DSP itself is generated by two different Faust
//! backends from one source — LLVM here, `-lang wasm-e` in the page — which is
//! the case that says whether a Faust def *means* the same thing in a tab as it
//! does in a window. Its tolerance is its own, and measured — `tests/parity.html`
//! carries both bars and says which scene is under which.
//!
//! The scene is deterministic (no noise) and the generator asserts the native
//! render contains no subnormal samples: wasm has no flush-to-zero mode, so
//! parity is only guaranteed on a denormal-free render (the recorded FTZ
//! parity policy). The page's bar is a tight tolerance rather than strict
//! bit-identity: native (system libm) and wasm (Rust's libm) round
//! transcendentals a few ULP apart — the posture tests/golden.rs records.

use std::path::Path;

use clausters::rosc::{OscBundle, OscMessage, OscPacket, OscTime, OscType, encoder};

const SAMPLE_RATE: f64 = 48000.0;
const CHANNELS: u32 = 2;
/// Both sides of the comparison pin the same seed. The scene has no noise in
/// it, so today this changes nothing — but a render is a fresh take by
/// default, and a parity fixture is exactly the case that wants the opposite.
/// `tests/parity.html` passes this same number.
const PARITY_SEED: u64 = 0x5041_5249_5459_0001;

fn msg(addr: &str, args: Vec<OscType>) -> OscPacket {
    OscPacket::Message(OscMessage {
        addr: addr.into(),
        args,
    })
}

/// A score timetag: seconds from the start of the render.
fn timetag(secs: f64) -> OscTime {
    OscTime {
        seconds: secs as u32,
        fractional: (secs.fract() * 2f64.powi(32)) as u32,
    }
}

/// One length-prefixed packet appended to the score byte stream.
fn push_packet(score: &mut Vec<u8>, packet: OscPacket) {
    let bytes = encoder::encode(&packet).expect("encodable packet");
    score.extend_from_slice(&(bytes.len() as i32).to_be_bytes());
    score.extend_from_slice(&bytes);
}

fn bundle_at(secs: f64, messages: Vec<OscPacket>) -> OscPacket {
    OscPacket::Bundle(OscBundle {
        timetag: timetag(secs),
        content: messages,
    })
}

/// Two overlapping voices of the built-in "default" def with a mid-block
/// retune — node tree, named controls and the sample-accurate scheduler,
/// kept short (0.5 s stereo) and denormal-free.
fn score_bytes() -> Vec<u8> {
    let s = |v: &str| OscType::String(v.into());
    let i = OscType::Int;
    let f = OscType::Float;
    let mut score = Vec::new();
    push_packet(
        &mut score,
        bundle_at(
            0.0,
            vec![msg(
                "/synth_new",
                vec![
                    s("default"),
                    i(1000),
                    i(0),
                    i(0),
                    s("freq"),
                    f(330.0),
                    s("amp"),
                    f(0.3),
                ],
            )],
        ),
    );
    push_packet(
        &mut score,
        bundle_at(
            0.11,
            vec![
                msg(
                    "/synth_new",
                    vec![
                        s("default"),
                        i(1001),
                        i(0),
                        i(0),
                        s("freq"),
                        f(440.0),
                        s("amp"),
                        f(0.2),
                    ],
                ),
                msg("/node_set", vec![i(1000), s("freq"), f(220.0)]),
            ],
        ),
    );
    push_packet(
        &mut score,
        bundle_at(0.3, vec![msg("/node_free", vec![i(1000)])]),
    );
    // Final bundle sets the render length.
    push_packet(
        &mut score,
        bundle_at(0.5, vec![msg("/node_free", vec![i(1001)])]),
    );
    score
}

/// A FaustDef score: one def sent at time 0, a voice on it, a `/node_set` on a
/// named control mid-render, and a close. The def is written in Faust source
/// rather than as a box or signal tree on purpose — those two are read by our
/// own interpreters, which are the *same program* on both targets, so a tree
/// would compare our interpreter against itself. The source path is the one
/// where the two Faust backends are all that differ.
fn faust_score_bytes() -> Vec<u8> {
    let s = |v: &str| OscType::String(v.into());
    let i = OscType::Int;
    let f = OscType::Float;
    // A resonant filter over a saw: a table-free oscillator (`os.sawtooth` is
    // computed, not read), a one-pole and a two-pole, all of which the two
    // backends emit as arithmetic rather than as data. Denormal-free: the gain
    // never decays.
    let dsp = r#"
        import("stdfaust.lib");
        freq = hslider("freq", 220, 50, 2000, 0.01);
        cut = hslider("cut", 1200, 100, 8000, 0.01);
        process = os.sawtooth(freq) : fi.resonlp(cut, 1.5, 0.3);
    "#;
    let mut score = Vec::new();
    push_packet(
        &mut score,
        bundle_at(
            0.0,
            vec![
                msg("/def_send", vec![s("faust"), s("parity_faust"), s(dsp)]),
                msg(
                    "/synth_new",
                    vec![s("parity_faust"), i(2000), i(0), i(0), s("freq"), f(220.0)],
                ),
            ],
        ),
    );
    push_packet(
        &mut score,
        bundle_at(
            0.17,
            vec![
                msg("/node_set", vec![i(2000), s("freq"), f(330.0)]),
                msg("/node_set", vec![i(2000), s("cut"), f(2400.0)]),
            ],
        ),
    );
    push_packet(
        &mut score,
        bundle_at(0.5, vec![msg("/node_free", vec![i(2000)])]),
    );
    score
}

/// Renders one scene natively, asserts it is denormal-free and writes the pair
/// the page compares: `<score>.bin` and `<take>.f32`.
fn emit(dir: &Path, score_name: &str, take_name: &str, score: &[u8]) -> usize {
    let (samples, _seed) = clausters_web::render(score, SAMPLE_RATE, CHANNELS, Some(PARITY_SEED))
        .expect("native render succeeds");
    let subnormals = samples.iter().filter(|x| x.is_subnormal()).count();
    assert_eq!(
        subnormals, 0,
        "the {score_name} parity scene must stay denormal-free (FTZ parity policy)"
    );
    std::fs::write(dir.join(format!("{score_name}.bin")), score).expect("write the score");
    let mut bytes = Vec::with_capacity(samples.len() * 4);
    for x in &samples {
        bytes.extend_from_slice(&x.to_le_bytes());
    }
    std::fs::write(dir.join(format!("{take_name}.f32")), &bytes).expect("write the take");
    samples.len()
}

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../clients/web/tests");
    std::fs::create_dir_all(&dir).expect("create clients/web/tests/");

    let score = score_bytes();
    let n = emit(&dir, "score", "native", &score);
    println!(
        "wrote clients/web/tests/score.bin ({} bytes) and native.f32 ({n} samples, {} ch, {} Hz)",
        score.len(),
        CHANNELS,
        SAMPLE_RATE
    );

    let faust = faust_score_bytes();
    let n = emit(&dir, "score-faust", "native-faust", &faust);
    println!(
        "wrote clients/web/tests/score-faust.bin ({} bytes) and native-faust.f32 ({n} samples)",
        faust.len(),
    );
}
