// Parity with the Python client on everything the sequencing layer computes.
//
// `clock-vectors.json` is generated by `gen-clock-vectors.py` from
// `clausters._native` (the Python client over `clausters-ffi`) and committed;
// here the TS client — reaching the *same* `clausters-core` through
// `crates/clausters-core-web` — must reproduce every value exactly. A
// divergence between the two clients is a failing test rather than a rumour.
//
// Exactness is the assertion nearly everywhere: the time arithmetic, the bar
// grid, the timetags, the pitch space and the seeded stream are the same
// operations on the same bits, so `assert.equal` is right and a tolerance
// there would hide a bug.
//
// The one documented exception is the **transcendental** builtins (`sin`,
// `exp`, `log`, `tanh`, and the music conversions built on them). Those go
// through libm, and wasm's differs from the native one in the last ulp — the
// posture `docs/decisions.md` records under "Native<->wasm render parity is a
// tight tolerance, not bit-identity". They are asserted within one f32 ulp;
// every other op stays exact, so a real divergence still fails.

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { loadCore } from "../src/base/core.ts";
import { TempoMap, tempoEnv } from "../src/base/time.ts";
import type { TimeUnit } from "../src/base/time.ts";
import {
    bar,
    beatInBar,
    quantDelay,
    samplesToSecs,
    secsToSamples,
    unixToNtp,
    unixToSample,
} from "../src/base/timebase.ts";
// The affine pair is the core's and the package deliberately does not wrap it
// (see `base/timebase.ts`): it takes a clock's own anchor triple, and under a
// changing tempo the map is the right answer. The parity that matters is
// against the core both clients call, so the test calls it directly rather
// than asking the package for a door that exists for nobody else.
import {
    beats_to_secs as beatsToSecs,
    secs_to_beats as secsToBeats,
} from "../src/core/clausters_core_web.js";
import { Rng } from "../src/base/rand.ts";
import * as builtins from "../src/base/builtins.ts";
import { degreeToMidinote } from "../src/base/builtins.ts";

interface Vectors {
    beatsToSecs: { tempo: number; baseBeats: number; baseSecs: number; beats: number; secs: number }[];
    secsToBeats: { tempo: number; baseBeats: number; baseSecs: number; secs: number; beats: number }[];
    secsToSamples: { secs: number; rate: number; samples: number }[];
    samplesToSecs: { samples: number; rate: number; secs: number }[];
    tempoMap: {
        build: (string | number)[][];
        segments: (number | string | null)[][];
        secsAt: { beats: number; secs: number }[];
        beatsAt: { secs: number; beats: number }[];
        tempoAt: { beats: number; tempo: number }[];
        spanSecs: { from: number; to: number; secs: number }[];
        spanBeats: { from: number; secs: number; beats: number }[];
        shapes: {
            curve: string | number;
            unit: string;
            segments: (number | string | null)[][];
            secsAt: { beats: number; secs: number }[];
            beatsAt: { secs: number; beats: number }[];
            tempoAt: { beats: number; tempo: number }[];
        }[];
    };
    quantDelay: { pos: number; quant: number; delay: number }[];
    bar: { beats: number; quant: number; bar: number; beatInBar: number }[];
    unixToNtp: { unix: number; ntp: string }[];
    unixToSample: {
        unix: number; anchorUnix: number; anchorSample: number; rate: number; sample: number;
    }[];
    degreeToMidinote: {
        degree: number; octave: number; root: number; scale: number[]; midinote: number;
    }[];
    unary: { op: string; x: number; y: number | string }[];
    binary: { op: string; a: number; b: number; y: number | string }[];
    rng: {
        seed: number; floats: number[]; below: number[]; childFloats: number[];
        afterSpawn: number[]; uniform: number[];
    }[];
}

/**
 * How many representable doubles apart two numbers are.
 *
 * The rest of this file asserts **equality**, and can: one implementation of
 * each formula answers both clients. A tempo *shape* is the one place that is
 * not enough, and the reason is not the formula but the library under it —
 * `exp` and `ln` are not bit-identical between a native libm and the one wasm
 * is built with, and the shapes evaluate them over a much wider range of
 * arguments than a straight ramp does. Measured over the shape vectors: **4 of
 * 189 values differ, by at most 3 ulp**, while the straight-ramp map above is
 * still 0 of 16. So the contract there is one formula, not one libm, and this
 * is what checks it.
 */
function ulpsApart(a: number, b: number): number {
    if (a === b) return 0;
    const view = new DataView(new ArrayBuffer(8));
    const bits = (x: number) => {
        view.setFloat64(0, x);
        return view.getBigInt64(0);
    };
    const [x, y] = [bits(a), bits(b)];
    return Number(x > y ? x - y : y - x);
}

/** `assert.equal` to within a few representable doubles. See {@link ulpsApart}. */
function assertClose(got: number, want: number, what: string): void {
    assert.ok(
        ulpsApart(got, want) <= 4,
        `${what}: ${got} is more than 4 ulp from ${want}`,
    );
}

/**
 * A segment's curve as the Python client spells it, back as the
 * `[shape, curvature]` pair the wasm side answers with.
 */
function shapeNumberOf(curve: number | string | null): [number, number] {
    if (typeof curve === "number") return [5, curve];
    if (curve === "linear") return [1, 0];
    if (curve === "exponential") return [2, 0];
    return [0, 0];
}

const here = new URL(".", import.meta.url);
const v: Vectors = JSON.parse(
    await readFile(new URL("clock-vectors.json", here), "utf8"),
);

await loadCore();

test("beat arithmetic matches the Python client", () => {
    for (const c of v.beatsToSecs) {
        assert.equal(beatsToSecs(c.tempo, c.baseBeats, c.baseSecs, c.beats), c.secs);
    }
    for (const c of v.secsToBeats) {
        assert.equal(secsToBeats(c.tempo, c.baseBeats, c.baseSecs, c.secs), c.beats);
    }
});

test("the piece's time map matches the Python client", () => {
    // The same map, built by the same calls in the same order — a step and a
    // ramp, which is the shape where a scalar tempo and the integral part
    // company. Equality, not approximation: there is one implementation of the
    // integral and both clients call it.
    const map = new TempoMap(1.0);
    assert.ok(map.push(2.0, 2.0));
    assert.ok(map.ramp(8.0, 16.0, 2.0, 4.0));

    assert.equal(map.len, v.tempoMap.segments.length);
    for (const [i, seg] of v.tempoMap.segments.entries()) {
        const got = map.segment(i);
        assert.ok(got);
        // The Python side reads a step's two ramp fields back as `null`; the
        // wasm side answers 0 for both, and the curve tag beside them is what
        // says which. Compare the four that always mean something, plus the
        // ramp's own ends when it has them.
        const [shape] = shapeNumberOf(seg[3]);
        assert.deepEqual([got[0], got[1], got[2], got[3]],
                         [seg[0], seg[1], seg[2], shape]);
        if (shape !== 0) assert.deepEqual([got[4], got[5]], [seg[4], seg[5]]);
    }
    for (const c of v.tempoMap.secsAt) assert.equal(map.secsAt(c.beats), c.secs);
    for (const c of v.tempoMap.beatsAt) assert.equal(map.beatsAt(c.secs), c.beats);
    for (const c of v.tempoMap.tempoAt) assert.equal(map.tempoAt(c.beats), c.tempo);
    for (const c of v.tempoMap.spanSecs) assert.equal(map.spanSecs(c.from, c.to), c.secs);
    for (const c of v.tempoMap.spanBeats) {
        assert.equal(map.spanBeats(c.from, c.secs), c.beats);
    }
});

test("every tempo shape matches the Python client, in both units", () => {
    // One envelope per shape, written by the same call in the same order. The
    // curvature is the one worth pinning: its inverse has no closed form and is
    // solved by iteration, so if either client iterated on its own this is
    // where the two would drift apart. Equality, not approximation.
    for (const c of v.tempoMap.shapes) {
        const map = new TempoMap(1.0);
        tempoEnv(map, 0.0, [1.0, 4.0, 2.0], [8.0, 4.0], c.curve, c.unit as TimeUnit);
        const where = `${c.curve} in ${c.unit}`;
        assert.equal(map.len, c.segments.length, where);
        for (const [i, seg] of c.segments.entries()) {
            const got = map.segment(i);
            assert.ok(got);
            const [shape, curvature] = shapeNumberOf(seg[3]);
            // The shape tag and the curvature are exact by construction: they
            // are what crossed, not what was computed.
            assert.deepEqual([got[3], got[6]], [shape, curvature], where);
            assertClose(got[0], seg[0] as number, `${where} segment ${i} beats`);
            assertClose(got[1], seg[1] as number, `${where} segment ${i} secs`);
            assertClose(got[2], seg[2] as number, `${where} segment ${i} tempo`);
            if (shape !== 0) {
                assertClose(got[4], seg[4] as number, `${where} segment ${i} end`);
                assertClose(got[5], seg[5] as number, `${where} segment ${i} endTempo`);
            }
        }
        for (const q of c.secsAt) assertClose(map.secsAt(q.beats), q.secs, `${where} secsAt`);
        for (const q of c.beatsAt) assertClose(map.beatsAt(q.secs), q.beats, `${where} beatsAt`);
        for (const q of c.tempoAt) assertClose(map.tempoAt(q.beats), q.tempo, `${where} tempoAt`);
    }
});

test("seconds and samples convert as the server rounds them", () => {
    for (const c of v.secsToSamples) {
        assert.equal(secsToSamples(c.secs, c.rate), c.samples);
    }
    for (const c of v.samplesToSecs) {
        assert.equal(samplesToSecs(c.samples, c.rate), c.secs);
    }
});

test("the quantization grid matches", () => {
    for (const c of v.quantDelay) assert.equal(quantDelay(c.pos, c.quant), c.delay);
    for (const c of v.bar) {
        assert.equal(bar(c.beats, c.quant), c.bar);
        assert.equal(beatInBar(c.beats, c.quant), c.beatInBar);
    }
});

test("timetags and sample targets match", () => {
    for (const c of v.unixToNtp) assert.equal(unixToNtp(c.unix), BigInt(c.ntp));
    for (const c of v.unixToSample) {
        assert.equal(
            unixToSample(c.unix, c.anchorUnix, c.anchorSample, c.rate),
            c.sample,
        );
    }
});

test("the pitch space resolves degrees identically", () => {
    for (const c of v.degreeToMidinote) {
        assert.equal(
            degreeToMidinote(c.degree, c.octave, c.root, c.scale),
            c.midinote,
        );
    }
});

// JSON has no NaN/Infinity literal, so the generator tags them; and `Object.is`
// is the comparison that holds for a NaN a builtin legitimately returns.
const expected = (y: number | string): number =>
    typeof y === "number"
        ? y
        : y === "nan"
          ? Number.NaN
          : y === "inf"
            ? Number.POSITIVE_INFINITY
            : Number.NEGATIVE_INFINITY;

/**
 * The ops that reach libm — the only ones allowed to differ from the native
 * client, and only in the last f32 ulp.
 */
const TRANSCENDENTAL = new Set([
    "sin", "cos", "tan", "asin", "acos", "atan", "atan2", "exp", "exp10",
    "log", "log2", "log10", "sinh", "cosh", "tanh", "pow", "hypot",
    "hypotapx", "midicps", "cpsmidi", "midiratio", "ratiomidi", "dbamp",
    "ampdb", "octcps", "cpsoct",
]);

/** One f32 ulp at `x` — the width of the disagreement libm is allowed. */
const ulp = (x: number): number => {
    const magnitude = Math.abs(Math.fround(x));
    if (!Number.isFinite(magnitude) || magnitude === 0) return 1e-45;
    return Math.pow(2, Math.floor(Math.log2(magnitude)) - 23);
};

function assertSame(op: string, got: number, want: number, what: string): void {
    if (Object.is(got, want)) return;
    if (TRANSCENDENTAL.has(op) && Number.isFinite(got) && Number.isFinite(want)) {
        assert.ok(
            Math.abs(got - want) <= ulp(want),
            `${what} = ${got}, expected ${want} (over one f32 ulp apart)`,
        );
        return;
    }
    assert.fail(`${what} = ${got}, expected ${want}`);
}

test("the builtins compute in f32, as the server does", () => {
    for (const c of v.unary) {
        const fn = (builtins as Record<string, unknown>)[c.op] as (x: number) => number;
        assertSame(c.op, fn(c.x), expected(c.y), `${c.op}(${c.x})`);
    }
    for (const c of v.binary) {
        const fn = (builtins as Record<string, unknown>)[c.op] as (
            a: number,
            b: number,
        ) => number;
        assertSame(c.op, fn(c.a, c.b), expected(c.y), `${c.op}(${c.a}, ${c.b})`);
    }
});

test("a builtin over a list extends the shorter operand cyclically", () => {
    assert.deepEqual(builtins.midicps([60, 72]), [
        builtins.midicps(60) as number,
        builtins.midicps(72) as number,
    ]);
    assert.deepEqual(builtins.add([1, 2, 3, 4], [10, 20]), [11, 22, 13, 24]);
    assert.deepEqual(builtins.mul([1, 2], 3), [3, 6]);
});

test("the seeded stream replays the Python client's values", () => {
    for (const run of v.rng) {
        const rng = new Rng(run.seed);
        for (const expected of run.floats) assert.equal(rng.nextF64(), expected);
        const bounds = [2, 7, 16, 1, 0];
        run.below.forEach((expected, i) => {
            assert.equal(rng.nextBelow(bounds[i]!), expected);
        });
        const child = rng.spawn();
        for (const expected of run.childFloats) assert.equal(child.nextF64(), expected);
        for (const expected of run.afterSpawn) assert.equal(rng.nextF64(), expected);
        for (const expected of run.uniform) assert.equal(rng.uniform(-1, 1), expected);
    }
});
