// Parity with the Python client on everything the sequencing layer computes.
//
// `clock-vectors.json` is generated by `gen-clock-vectors.py` from
// `clausters._native` (the Python client over `clausters-ffi`) and committed;
// here the TS client — reaching the *same* `clausters-core` through
// `crates/clausters-core-web` — must reproduce every value exactly. A
// divergence between the two clients is a failing test rather than a rumour.
//
// Exactness is the assertion nearly everywhere: the time arithmetic, the bar
// grid, the timetags, the pitch space and the seeded stream are the same
// operations on the same bits, so `assert.equal` is right and a tolerance
// there would hide a bug.
//
// The one documented exception is the **transcendental** builtins (`sin`,
// `exp`, `log`, `tanh`, and the music conversions built on them). Those go
// through libm, and wasm's differs from the native one in the last ulp — the
// posture `docs/decisions.md` records under "Native<->wasm render parity is a
// tight tolerance, not bit-identity". They are asserted within one f32 ulp;
// every other op stays exact, so a real divergence still fails.

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { loadCore } from "../src/base/core.ts";
import {
    bar,
    beatInBar,
    beatsToSecs,
    quantDelay,
    samplesToSecs,
    secsToBeats,
    secsToSamples,
    unixToNtp,
    unixToSample,
} from "../src/base/timebase.ts";
import { Rng } from "../src/base/rand.ts";
import * as builtins from "../src/base/builtins.ts";
import { degreeToMidinote } from "../src/base/builtins.ts";

interface Vectors {
    beatsToSecs: { tempo: number; baseBeats: number; baseSecs: number; beats: number; secs: number }[];
    secsToBeats: { tempo: number; baseBeats: number; baseSecs: number; secs: number; beats: number }[];
    secsToSamples: { secs: number; rate: number; samples: number }[];
    samplesToSecs: { samples: number; rate: number; secs: number }[];
    quantDelay: { pos: number; quant: number; delay: number }[];
    bar: { beats: number; quant: number; bar: number; beatInBar: number }[];
    unixToNtp: { unix: number; ntp: string }[];
    unixToSample: {
        unix: number; anchorUnix: number; anchorSample: number; rate: number; sample: number;
    }[];
    degreeToMidinote: {
        degree: number; octave: number; root: number; scale: number[]; midinote: number;
    }[];
    unary: { op: string; x: number; y: number | string }[];
    binary: { op: string; a: number; b: number; y: number | string }[];
    rng: {
        seed: number; floats: number[]; below: number[]; childFloats: number[];
        afterSpawn: number[]; uniform: number[];
    }[];
}

const here = new URL(".", import.meta.url);
const v: Vectors = JSON.parse(
    await readFile(new URL("clock-vectors.json", here), "utf8"),
);

await loadCore();

test("beat arithmetic matches the Python client", () => {
    for (const c of v.beatsToSecs) {
        assert.equal(beatsToSecs(c.tempo, c.baseBeats, c.baseSecs, c.beats), c.secs);
    }
    for (const c of v.secsToBeats) {
        assert.equal(secsToBeats(c.tempo, c.baseBeats, c.baseSecs, c.secs), c.beats);
    }
});

test("seconds and samples convert as the server rounds them", () => {
    for (const c of v.secsToSamples) {
        assert.equal(secsToSamples(c.secs, c.rate), c.samples);
    }
    for (const c of v.samplesToSecs) {
        assert.equal(samplesToSecs(c.samples, c.rate), c.secs);
    }
});

test("the quantization grid matches", () => {
    for (const c of v.quantDelay) assert.equal(quantDelay(c.pos, c.quant), c.delay);
    for (const c of v.bar) {
        assert.equal(bar(c.beats, c.quant), c.bar);
        assert.equal(beatInBar(c.beats, c.quant), c.beatInBar);
    }
});

test("timetags and sample targets match", () => {
    for (const c of v.unixToNtp) assert.equal(unixToNtp(c.unix), BigInt(c.ntp));
    for (const c of v.unixToSample) {
        assert.equal(
            unixToSample(c.unix, c.anchorUnix, c.anchorSample, c.rate),
            c.sample,
        );
    }
});

test("the pitch space resolves degrees identically", () => {
    for (const c of v.degreeToMidinote) {
        assert.equal(
            degreeToMidinote(c.degree, c.octave, c.root, c.scale),
            c.midinote,
        );
    }
});

// JSON has no NaN/Infinity literal, so the generator tags them; and `Object.is`
// is the comparison that holds for a NaN a builtin legitimately returns.
const expected = (y: number | string): number =>
    typeof y === "number"
        ? y
        : y === "nan"
          ? Number.NaN
          : y === "inf"
            ? Number.POSITIVE_INFINITY
            : Number.NEGATIVE_INFINITY;

/**
 * The ops that reach libm — the only ones allowed to differ from the native
 * client, and only in the last f32 ulp.
 */
const TRANSCENDENTAL = new Set([
    "sin", "cos", "tan", "asin", "acos", "atan", "atan2", "exp", "exp10",
    "log", "log2", "log10", "sinh", "cosh", "tanh", "pow", "hypot",
    "hypotapx", "midicps", "cpsmidi", "midiratio", "ratiomidi", "dbamp",
    "ampdb", "octcps", "cpsoct",
]);

/** One f32 ulp at `x` — the width of the disagreement libm is allowed. */
const ulp = (x: number): number => {
    const magnitude = Math.abs(Math.fround(x));
    if (!Number.isFinite(magnitude) || magnitude === 0) return 1e-45;
    return Math.pow(2, Math.floor(Math.log2(magnitude)) - 23);
};

function assertSame(op: string, got: number, want: number, what: string): void {
    if (Object.is(got, want)) return;
    if (TRANSCENDENTAL.has(op) && Number.isFinite(got) && Number.isFinite(want)) {
        assert.ok(
            Math.abs(got - want) <= ulp(want),
            `${what} = ${got}, expected ${want} (over one f32 ulp apart)`,
        );
        return;
    }
    assert.fail(`${what} = ${got}, expected ${want}`);
}

test("the builtins compute in f32, as the server does", () => {
    for (const c of v.unary) {
        const fn = (builtins as Record<string, unknown>)[c.op] as (x: number) => number;
        assertSame(c.op, fn(c.x), expected(c.y), `${c.op}(${c.x})`);
    }
    for (const c of v.binary) {
        const fn = (builtins as Record<string, unknown>)[c.op] as (
            a: number,
            b: number,
        ) => number;
        assertSame(c.op, fn(c.a, c.b), expected(c.y), `${c.op}(${c.a}, ${c.b})`);
    }
});

test("a builtin over a list extends the shorter operand cyclically", () => {
    assert.deepEqual(builtins.midicps([60, 72]), [
        builtins.midicps(60) as number,
        builtins.midicps(72) as number,
    ]);
    assert.deepEqual(builtins.add([1, 2, 3, 4], [10, 20]), [11, 22, 13, 24]);
    assert.deepEqual(builtins.mul([1, 2], 3), [3, 6]);
});

test("the seeded stream replays the Python client's values", () => {
    for (const run of v.rng) {
        const rng = new Rng(run.seed);
        for (const expected of run.floats) assert.equal(rng.nextF64(), expected);
        const bounds = [2, 7, 16, 1, 0];
        run.below.forEach((expected, i) => {
            assert.equal(rng.nextBelow(bounds[i]!), expected);
        });
        const child = rng.spawn();
        for (const expected of run.childFloats) assert.equal(child.nextF64(), expected);
        for (const expected of run.afterSpawn) assert.equal(rng.nextF64(), expected);
        for (const expected of run.uniform) assert.equal(rng.uniform(-1, 1), expected);
    }
});
