// Parity with the Python client on every **projection**.
//
// A projection is what an editable structure owes an endpoint: the props a host
// draws it with, the payloads an edit becomes, the operations that make a
// server sound it. There is one implementation of each, in `clausters-editing`,
// and this is what holds the two clients to it — `editing-vectors.json` is
// generated by `gen-editing-vectors.py` from `clausters._native` (the Python
// client over `clausters-ffi`), and here the same questions go through wasm.
//
// It is worth the file because the failure it catches is invisible everywhere
// else: two clients drawing one curve two ways is not a build error, not a type
// error and not a lint — it is two payloads nobody put side by side.
//
// Exactness is the assertion. A curve's axis is arithmetic on the same bits
// through the same crate, so a tolerance here would only hide a divergence.

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { loadCore } from "../src/base/core.ts";
import { MultitrackEditor, MultitrackView } from "../src/gui/editing/index.ts";
import { Multitrack } from "../src/multitrack.ts";
import {
    conversationAnswer,
    conversationRead,
    editingIntake,
    multitrackNames,
    multitrackProps,
    pointsProps,
} from "../src/core/clausters_core_web.js";

type Vector = {
    name: string;
    kind:
        | "points_props"
        | "multitrack_props"
        | "intake"
        | "conversation"
        | "answer"
        | "names"
        | "editor_exchange";
    // `editor_exchange`
    controls?: Record<string, number>;
    turns?: {
        name: string;
        target: string;
        seq: number;
        against: number | "now";
        tag: string;
        values: unknown[];
        changed: boolean;
        messages: unknown[];
        playback: unknown[];
        regions: unknown[];
    }[];
    props?: Record<string, unknown>;
    // `points_props`
    points?: number[];
    kept?: [number, number] | null;
    held?: number;
    // `multitrack_props`
    multitrack?: unknown;
    rate?: number;
    bpm?: number;
    sources?: Record<string, unknown>;
    // `intake`
    domain?: string;
    tag?: string;
    request?: Record<string, unknown>;
    intake?: Record<string, unknown>;
    // `conversation`
    message?: Record<string, unknown>;
    turn?: Record<string, unknown>;
    applied?: number | null;
    after?: { floor: number; applied: number };
    // `answer`
    seq?: number;
    docVersion?: number;
    reason?: string | null;
    corrections?: unknown[];
    answer?: Record<string, unknown>;
    // `names`
    names?: Record<string, unknown>;
};

const vectors = JSON.parse(
    await readFile(new URL("./editing-vectors.json", import.meta.url), "utf8"),
) as Vector[];

const of = (kind: Vector["kind"]) => vectors.filter((v) => v.kind === kind);

test("a curve's props are the same props in both clients", async () => {
    await loadCore();
    const cases = of("points_props");
    assert.ok(cases.length > 0, "the vectors were generated");
    for (const v of cases) {
        const got = JSON.parse(
            pointsProps(
                Float64Array.from(v.points ?? []),
                v.kept?.[0],
                v.kept?.[1],
                v.held,
            ),
        ) as Record<string, unknown>;
        assert.deepEqual(got, v.props, v.name);
    }
});

test("and a multitrack's props are the same props in both clients", async () => {
    await loadCore();
    const cases = of("multitrack_props");
    assert.ok(cases.length > 0, "the vectors were generated");
    for (const v of cases) {
        const got = JSON.parse(
            multitrackProps(
                JSON.stringify(v.multitrack),
                v.rate ?? 0,
                JSON.stringify(v.sources ?? {}),
            ),
        ) as Record<string, unknown>;
        assert.deepEqual(got, v.props, v.name);
    }
});

test("and a gesture means the same thing in both clients", async () => {
    await loadCore();
    const cases = of("intake");
    assert.ok(cases.length > 0, "the vectors were generated");
    for (const v of cases) {
        const got = JSON.parse(
            editingIntake(v.domain ?? "", v.tag ?? "", JSON.stringify(v.request ?? {})),
        ) as Record<string, unknown>;
        assert.deepEqual(got, v.intake, v.name);
    }
});

test("and a recorded exchange comes to the same turns in both clients", async () => {
    // The acceptance of the conversation milestone, stated as data: **the host
    // cannot tell which client it is talking to from the message sequence.** The
    // exchange is replayed as a fold, `applied` and all — that field is part of
    // the protocol, not bookkeeping, since it is what turns "the version moved"
    // into "it moved by someone *else*".
    await loadCore();
    const cases = of("conversation");
    assert.ok(cases.length > 0, "the vectors were generated");
    let state = { floor: 1, applied: 1 };
    for (const v of cases) {
        const answered = JSON.parse(
            conversationRead(JSON.stringify(state), JSON.stringify(v.message ?? {})),
        ) as { turn: Record<string, unknown>; state: { floor: number; applied: number } };
        assert.deepEqual(answered.turn, v.turn, v.name);
        state = answered.state;
        if (v.applied !== null && v.applied !== undefined) {
            state = { ...state, applied: v.applied };
        }
        assert.deepEqual(state, v.after, v.name);
    }
});

test("and an answer is the same message in both clients", async () => {
    await loadCore();
    const cases = of("answer");
    assert.ok(cases.length > 0, "the vectors were generated");
    for (const v of cases) {
        const got = JSON.parse(conversationAnswer(JSON.stringify({
            seq: v.seq,
            docVersion: v.docVersion,
            reason: v.reason ?? null,
            corrections: v.corrections ?? [],
        }))) as Record<string, unknown>;
        assert.deepEqual(got, v.answer, v.name);
    }
});

test("and the multitrack editor answers a recorded exchange the same in both clients", async () => {
    // The acceptance of the multitrack application, stated as data: each client
    // holds a handle over the applications crate and carries out what it
    // answers, so a hand's gestures come to the same messages to the host, the
    // same calls on the playback and the same multitrack whichever client carries
    // them. The gestures ran through the Python client's `MultitrackEditor` and
    // run here through this one's; widgets are named by role, since which id an
    // allocator hands out is each client's own.
    await loadCore();
    const [v] = of("editor_exchange");
    assert.ok(v !== undefined, "the vectors were generated");
    const multitrack = Multitrack.read(v.multitrack as Record<string, unknown>);
    const ed = new MultitrackEditor(multitrack, {
        sampleRate: v.rate ?? 48_000,
        sources: v.sources as Record<number, number>,
    });
    type Message = [string, number, number, string | null, [unknown, unknown][]];
    const messages: Message[] = [];
    const host = {
        ack(seq: number, docVersion = 0, _generations: unknown = [], reason?: string) {
            messages.push(["ack", seq, docVersion, reason ?? null, []]);
        },
        push(
            seq: number,
            sets: [number, unknown][],
            docVersion = 0,
            _generations: unknown = [],
            reason?: string,
        ) {
            messages.push(["push", seq, docVersion, reason ?? null, sets.map(([w, p]) => [w, p])]);
        },
        set() {},
    };
    const calls: unknown[][] = [];
    const playback = {
        playing: false,
        meters: new Map<number, [number, number]>(),
        refresh: () => Promise.resolve(),
        play() {
            calls.push(["play"]);
            this.playing = true;
            return Promise.resolve();
        },
        pause() {
            calls.push(["pause"]);
            this.playing = false;
        },
        stop() {
            calls.push(["stop"]);
            this.playing = false;
        },
        cue(beat: number) {
            calls.push(["cue", beat]);
        },
        sync() {
            calls.push(["sync"]);
        },
    };
    const inner = ed as unknown as {
        app: { host: unknown };
        windowId: number | null;
        controls: Record<string, number>;
        version: number;
        playback: unknown;
    };
    inner.app.host = host;
    inner.windowId = 1;
    inner.playback = playback;
    ed.draw();
    inner.controls = { ...(v.controls as Record<string, number>) };
    const view = ed.view as MultitrackView;
    const ids: Record<string, number> = {
        multitrack: view.multitrack!,
        ruler: view.ruler!,
        window: 1,
        ...(v.controls as Record<string, number>),
    };
    const roles = new Map<unknown, string>([[view.multitrack, "multitrack"], [view.ruler, "ruler"]]);
    for (const turn of v.turns ?? []) {
        messages.length = 0;
        calls.length = 0;
        const against = turn.against === "now" ? inner.version : turn.against;
        const changed = ed.apply("/gui_event", [
            ids[turn.target],
            turn.seq,
            against,
            turn.tag,
            ...turn.values,
        ]);
        // A toggle asks the engine first, which in a page is a promise.
        await new Promise((resolve) => setTimeout(resolve, 0));
        assert.equal(changed, turn.changed, turn.name);
        assert.deepEqual(
            messages.map(([kind, seq, version, reason, sets]) => [
                kind,
                seq,
                version,
                reason,
                sets.map(([w, p]) => [roles.get(w) ?? w, p]),
            ]),
            turn.messages,
            turn.name,
        );
        assert.deepEqual(calls, turn.playback, turn.name);
        assert.deepEqual(
            multitrack.tracks.flatMap((t) =>
                t.lanes.flatMap((l) => l.regions.map((r) => [t.id, r.id, r.position, r.length]))
            ),
            turn.regions,
            turn.name,
        );
    }
});

test("and a multitrack calls its rows and boxes the same in both clients", async () => {
    await loadCore();
    const cases = of("names");
    assert.ok(cases.length > 0, "the vectors were generated");
    for (const v of cases) {
        const got = JSON.parse(multitrackNames(JSON.stringify(v.multitrack))) as Record<
            string,
            unknown
        >;
        assert.deepEqual(got, v.names, v.name);
    }
});
