// Parity with the Python client on every **projection**.
//
// A projection is what an editable structure owes an endpoint: the props a host
// draws it with, the payloads an edit becomes, the operations that make a
// server sound it. There is one implementation of each, in `clausters-editing`,
// and this is what holds the two clients to it — `editing-vectors.json` is
// generated by `gen-editing-vectors.py` from `clausters._native` (the Python
// client over `clausters-ffi`), and here the same questions go through wasm.
//
// It is worth the file because the failure it catches is invisible everywhere
// else: two clients drawing one curve two ways is not a build error, not a type
// error and not a lint — it is two payloads nobody put side by side.
//
// Exactness is the assertion. A curve's axis is arithmetic on the same bits
// through the same crate, so a tolerance here would only hide a divergence.

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { loadCore } from "../src/base/core.ts";
import { editingIntake, multitrackProps, pointsProps } from "../src/core/clausters_core_web.js";

type Vector = {
    name: string;
    kind: "points_props" | "multitrack_props" | "intake";
    props?: Record<string, unknown>;
    // `points_props`
    points?: number[];
    kept?: [number, number] | null;
    held?: number;
    // `multitrack_props`
    piece?: unknown;
    rate?: number;
    bpm?: number;
    sources?: Record<string, unknown>;
    // `intake`
    domain?: string;
    tag?: string;
    request?: Record<string, unknown>;
    intake?: Record<string, unknown>;
};

const vectors = JSON.parse(
    await readFile(new URL("./editing-vectors.json", import.meta.url), "utf8"),
) as Vector[];

const of = (kind: Vector["kind"]) => vectors.filter((v) => v.kind === kind);

test("a curve's props are the same props in both clients", async () => {
    await loadCore();
    const cases = of("points_props");
    assert.ok(cases.length > 0, "the vectors were generated");
    for (const v of cases) {
        const got = JSON.parse(
            pointsProps(
                Float64Array.from(v.points ?? []),
                v.kept?.[0],
                v.kept?.[1],
                v.held,
            ),
        ) as Record<string, unknown>;
        assert.deepEqual(got, v.props, v.name);
    }
});

test("and a piece's props are the same props in both clients", async () => {
    await loadCore();
    const cases = of("multitrack_props");
    assert.ok(cases.length > 0, "the vectors were generated");
    for (const v of cases) {
        const got = JSON.parse(
            multitrackProps(
                JSON.stringify(v.piece),
                v.rate ?? 0,
                v.bpm ?? 0,
                JSON.stringify(v.sources ?? {}),
            ),
        ) as Record<string, unknown>;
        assert.deepEqual(got, v.props, v.name);
    }
});

test("and a gesture means the same thing in both clients", async () => {
    await loadCore();
    const cases = of("intake");
    assert.ok(cases.length > 0, "the vectors were generated");
    for (const v of cases) {
        const got = JSON.parse(
            editingIntake(v.domain ?? "", v.tag ?? "", JSON.stringify(v.request ?? {})),
        ) as Record<string, unknown>;
        assert.deepEqual(got, v.intake, v.name);
    }
});
