// Encode/decode parity with the Python client's reference codec.
//
// `osc-vectors.json` and `osc-decode-vectors.json` are generated by `gen-osc-vectors.py` from
// `clausters.base._osclib` (the Python client) and committed; here the
// core-backed TS codec must reproduce every packet byte for byte, and read
// its own bytes back to the same values. Run: `npm test` (node --test strips
// the types natively). The core wasm is loaded from the staged `core/`
// bundle as raw bytes — node's `fetch` cannot read `file://` URLs.

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { loadOsc, encodeMessage, decodePacket } from "../src/base/osc.ts";
import type { OscArg } from "../src/base/osc.ts";

interface Vector {
    name: string;
    addr: string;
    args: [string, number | string][];
    hex: string;
}

const here = new URL(".", import.meta.url);
const vectors: Vector[] = JSON.parse(
    await readFile(new URL("osc-vectors.json", here), "utf8"),
);

/** A packet and what the Python client's decoder reads out of it. */
interface DecodeVector {
    name: string;
    addr: string;
    args: number[];
    hex: string;
}

const decodeVectors: DecodeVector[] = JSON.parse(
    await readFile(new URL("osc-decode-vectors.json", here), "utf8"),
);

const fromHex = (hex: string): Uint8Array =>
    new Uint8Array((hex.match(/../g) ?? []).map((b) => parseInt(b, 16)));
const toHex = (bytes: Uint8Array): string =>
    [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");

// JSON carries blobs as hex strings; rebuild the codec's tagged form.
const toArgs = (raw: Vector["args"]): OscArg[] =>
    raw.map(([tag, value]) =>
        tag === "b"
            ? ["b", fromHex(value as string)]
            : ([tag, value] as OscArg),
    );

await loadOsc();

test("encode parity with the Python reference", () => {
    for (const vector of vectors) {
        assert.equal(
            toHex(encodeMessage(vector.addr, toArgs(vector.args))),
            vector.hex,
            `vector ${vector.name}`,
        );
    }
});

test("decode reads the reference bytes back", () => {
    for (const vector of vectors) {
        const messages = decodePacket(fromHex(vector.hex));
        assert.equal(messages.length, 1, `vector ${vector.name}`);
        const { addr, args } = messages[0];
        assert.equal(addr, vector.addr, `vector ${vector.name}`);
        assert.equal(args.length, vector.args.length, `vector ${vector.name}`);
        vector.args.forEach(([tag, value], i) => {
            const got = args[i];
            if (tag === "b") {
                assert.ok(got instanceof Uint8Array, `vector ${vector.name}`);
                assert.equal(toHex(got), value, `vector ${vector.name}[${i}]`);
            } else if (tag === "f") {
                // float32 round-trips through the wire's precision.
                assert.ok(
                    Math.abs((got as number) - (value as number)) <=
                        Math.abs(value as number) * 1e-6,
                    `vector ${vector.name}[${i}]: ${got} != ${value}`,
                );
            } else {
                assert.equal(got, value, `vector ${vector.name}[${i}]`);
            }
        });
    }
});

test("decode parity for values the Python encoder cannot build", () => {
    // The timetag argument, which encode parity never reaches: it is what
    // `/clock_query.reply` carries its anchor in, and it crosses to JS as
    // **Unix** seconds — the value the Python decoder yields for the same
    // bytes, not the raw NTP epoch.
    for (const vector of decodeVectors) {
        const messages = decodePacket(fromHex(vector.hex));
        assert.equal(messages.length, 1, `vector ${vector.name}`);
        assert.equal(messages[0]!.addr, vector.addr, `vector ${vector.name}`);
        const args = messages[0]!.args as number[];
        assert.equal(args.length, vector.args.length, `vector ${vector.name}`);
        vector.args.forEach((value, i) => {
            assert.ok(
                Math.abs(args[i]! - value) <= Math.abs(value) * 1e-12,
                `vector ${vector.name}[${i}]: ${args[i]} != ${value}`,
            );
        });
    }
});
