// The offline drive: one piece, one score — and the samples it renders to.
//
// `score-vectors.json` is generated by `gen-score-vectors.py` from the Python
// client's own NRT sessions and committed; here the same three pieces are
// written with this client and the accumulated score must come out **byte for
// byte** the same. That is W13's acceptance, and it asserts the whole offline
// stack at once: the score epoch's timetag packing, the ordering rule, the
// bundle framing, the beat-to-second mapping and every command's argument
// tagging.
//
// The pieces are written twice by hand — once in the generator, once here —
// because a generated pair would only prove the generator agrees with itself.
// They play the server's **built-in** instrument and send no def: a def's wire
// payload is JSON text the two serializers lay out differently (spacing, and
// `440.0` against `440`), which is a formatting difference `def-parity.test.ts`
// already pins by comparing the parsed spec. Letting it in here would replace
// a meaningful byte comparison with a formatting one.
//
// The render half runs the engine's own wasm renderer over a score this client
// wrote, so the drive is checked end to end: score in, samples out.

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { loadOsc } from "../src/base/osc.ts";
import { Routine } from "../src/base/stream.ts";
import { Session } from "../src/session.ts";
import { ScoreConnection } from "../src/base/connection.ts";
import { Synth } from "../src/defs/node.ts";
import { SynthDef } from "../src/defs/synthdef.ts";
import { Env, control, out, sine } from "../src/defs/ugens/index.ts";
import { Event, Pbind, Pseq } from "../src/seq/index.ts";
import { loadRenderer } from "../src/engine/render.ts";
import { render } from "../src/render.ts";

const here = new URL(".", import.meta.url);

await loadOsc();
await loadRenderer(await readFile(new URL("../dist/engine/clausters_web_bg.wasm", here)));

interface Vector {
    name: string;
    tempo: number;
    hex: string;
}

interface EnvVector {
    name: string;
    frames: number;
    channels: number;
    sample_rate: number;
    trace: number[];
}

const { scores: vectors, envelopes }: {
    scores: Vector[];
    envelopes: EnvVector[];
} = JSON.parse(await readFile(new URL("score-vectors.json", here), "utf8"));

const toHex = (bytes: Uint8Array): string =>
    [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");

/** The pieces, by the generator's names. */
const pieces: Record<string, (session: Session) => void> = {
    one_synth(session) {
        const server = session.server;
        const node = new Synth("default", { freq: 330.0 }, { server });
        server.sendBundleAfter(1.0, [["/node_free", ["i", node.id]]]);
    },
    routine(session) {
        const server = session.server;
        new Routine(function* () {
            for (const freq of [440.0, 550.0, 660.0]) {
                new Event({ freq, dur: 0.5, amp: 0.2 }).play(server);
                yield 0.5;
            }
        }).play(session.clock);
    },
    pattern(session) {
        new Pbind({
            degree: new Pseq([0, 2, 4]),
            dur: 0.25,
            amp: 0.15,
        }).play(session.server, { clock: session.clock });
    },
};

test("a piece writes the same score the Python client writes", async () => {
    for (const vector of vectors) {
        const session = await Session.nrt({ tempo: vector.tempo });
        session.use(() => {
            pieces[vector.name]!(session);
            session.clock.render();
        });
        const score = (session.server.connection as ScoreConnection).score.bytes();
        assert.equal(toHex(score), vector.hex, `piece ${vector.name}`);
    }
});

test("an offline session renders the score it wrote", async () => {
    const session = await Session.nrt({ tempo: 1.0 });
    session.use(() => {
        pieces.one_synth!(session);
    });
    const stats = await session.render({ channels: 1 });
    // The score frees the node a second in, and a render stops when its score
    // does — so the length is the piece's, not a number passed in.
    assert.equal(stats.frames, 48_000, "one second at the default rate");
    assert.equal(stats.channels, 1);
    assert.ok(stats.peak[0]! > 0.15, `silent render (peak ${stats.peak[0]})`);
    assert.ok(
        Math.abs(stats.rms[0]! - stats.peak[0]! / Math.SQRT2) < 0.01,
        "a sine's RMS is its peak over root two",
    );
});

test("the seed is the take, and handing it back replays it", async () => {
    // Noise, so the seed has something to govern: two takes of this differ
    // unless one is asked to repeat the other.
    const { whiteNoise } = await import("../src/defs/ugens/index.ts");
    const noisy = () => new SynthDef("score_noise", out(0.0, whiteNoise().mul(0.2)));

    const first = await render(noisy(), { dur: 0.1, channels: 1 });
    const fresh = await render(noisy(), { dur: 0.1, channels: 1 });
    // A render with no seed draws one. On wasm the engine has no entropy
    // source, so the client forwards a word from the platform that does —
    // without that, every take here would be the same take.
    assert.notEqual(fresh.seed, first.seed, "a seedless render is a new take");
    assert.notDeepEqual([...fresh.samples], [...first.samples]);

    const again = await render(noisy(), { dur: 0.1, channels: 1, seed: first.seed });
    assert.equal(again.seed, first.seed);
    assert.deepEqual([...again.samples], [...first.samples]);
});

test("a bare expression renders through the ephemeral-def coercion", async () => {
    const stats = await render(sine(440.0).mul(0.5), { dur: 0.5, channels: 1 });
    assert.equal(stats.frames, 24_000);
    assert.ok(Math.abs(stats.peak[0]! - 0.5) < 0.01, `peak ${stats.peak[0]}`);
    assert.equal(stats.duration, 0.5);
});

test("an expression wider than the render's outputs is refused", async () => {
    const { ChannelList } = await import("../src/defs/ugens/index.ts");
    const stereo = new ChannelList([sine(440.0), sine(550.0)]);
    await assert.rejects(
        () => render(stereo, { dur: 0.1, channels: 1 }),
        /writes 2 channels but the render has 1/,
    );
});

test("a pattern bounces offline, and `until` is what bounds an endless one", async () => {
    const bounced = await render(
        new Pbind({
            instrument: "default",
            degree: new Pseq([0, 2, 4]),
            dur: 0.25,
            amp: 0.2,
        }),
        { channels: 1 },
    );
    assert.ok(bounced.frames > 0, "the bounce produced audio");
    assert.ok(bounced.peak[0]! > 0.05, `silent bounce (peak ${bounced.peak[0]})`);

    // An endless source drains only because `until` stops the clock: without
    // it this call would never return, which is why the option is the
    // caller's responsibility rather than a guess the verb makes.
    const endless = await render(
        new Pbind({ instrument: "default", degree: new Pseq([0, 2], Infinity), dur: 0.25 }),
        { channels: 1, until: 2.0 },
    );
    assert.ok(endless.frames > 0);
    // Two beats of quarter notes, plus the last note's own sustain — bounded
    // by the drain, not by the pattern, which has no end.
    assert.ok(
        endless.duration > 2.0 && endless.duration < 3.5,
        `the bound did not hold: ${endless.duration}s`,
    );
});

test("an envelope draws what an EnvGen plays, in both clients", async () => {
    // `plot(Env)` renders the curve through the engine's own `envGen` rather
    // than re-evaluating the break points here — so this compares the drawn
    // curve itself against the Python client's, decimated to its shape.
    const { renderEnvSamples } = await import("../src/plot.ts");
    const builders: Record<string, Env> = {
        adsr: Env.adsr(),
        perc: Env.perc(0.01, 0.5),
        triangle: new Env([0.0, 1.0, 0.0], [0.25, 0.25]),
    };
    for (const vector of envelopes) {
        const drawn = await renderEnvSamples(builders[vector.name]!, vector.sample_rate);
        assert.equal(drawn.channels, vector.channels, `envelope ${vector.name}`);
        assert.equal(drawn.samples.length, vector.frames, `envelope ${vector.name}`);
        const step = Math.max(1, Math.floor(drawn.samples.length / vector.trace.length));
        vector.trace.forEach((expected, i) => {
            const got = drawn.samples[i * step]!;
            assert.ok(
                Math.abs(got - expected) < 1e-5,
                `envelope ${vector.name}[${i * step}]: ${got} != ${expected}`,
            );
        });
    }
});
