//! Forward and inverse real FFT shared by the server and the GUI clients.
//!
//! Both the GUI spectrogram (its STFT) and the server's `FFT`/`IFFT` UGens
//! need a forward FFT over a power-of-two window. Keeping the algorithm
//! here means **one implementation, identical results**, in the shared core --
//! the rule that an algorithm used by more than one process lives once. It
//! wraps [`microfft`], which is `no_std` and **zero-allocation** with
//! compile-time power-of-two sizes (exactly the STFT's window sizes), so a
//! real-time caller never allocates inside `process` -- the property the future
//! UGens require.
//!
//! `microfft` provides **both** directions: `real::rfft_*` (forward, real
//! input) and `inverse::ifft_*` (inverse complex FFT, normalized by `1/N`).
//! This module exposes three surfaces over them:
//!
//! - [`rfft_magnitudes_into`] -- the half-spectrum magnitudes the spectrogram
//!   draws.
//! - [`rfft_into`] -- a **forward** transform packing the complex frame in the
//!   canonical spectral-buffer layout `[dc, nyquist, re1, im1, ...]` (scsynth's
//!   `FFT` buffer format), the wire the server's `FFT`->`PV_*`->`IFFT` chain
//!   passes between its UGens.
//! - [`irfft_into`] -- the matching **inverse**: it folds the packed
//!   half-frame into an `n/2`-point complex spectrum whose inverse holds the
//!   even samples in its real part and the odd ones in its imaginary part --
//!   the forward transform's own trick run backwards, half the work of
//!   rebuilding the full Hermitian spectrum -- producing the real time-domain
//!   frame for overlap-add resynthesis.
//!
//! All three are zero-allocation (the transforms run in stack buffers), so the
//! server's UGens call them per hop on the audio thread without allocating.

use microfft::{Complex32, inverse, real};

/// `e^{+j 2 pi k / TWIDDLE_N}` for `k` in `0..TWIDDLE_N / 2`, generated by
/// the build script in `f64` and rounded once.
mod twiddle {
    include!(concat!(env!("OUT_DIR"), "/twiddle.rs"));
}

/// The transform size the twiddle table is laid out for: the largest
/// supported one. A size `n` reads it at a stride of `TWIDDLE_N / n`.
const TWIDDLE_N: usize = 4096;

/// The window sizes [`rfft_magnitudes_into`] accepts: the powers of two
/// `microfft` is built for, up to its default `size-4096`.
pub const SUPPORTED_SIZES: &[usize] = &[256, 512, 1024, 2048, 4096];

/// Whether a window of `n` samples is a supported FFT size.
pub fn supports(n: usize) -> bool {
    SUPPORTED_SIZES.contains(&n)
}

/// Forward real FFT magnitudes of `input` into `mags`.
///
/// `input.len()` must be a [supported](SUPPORTED_SIZES) power of two `n` and
/// `mags.len()` must be `n / 2`. On success `mags[b]` is the magnitude of bin
/// `b` for `b` in `0..n/2`: bin 0 is the DC magnitude `|X[0]|` (the real Nyquist
/// term, which `microfft` packs into the DC bin's imaginary part, is not
/// returned -- matching the half-spectrum the spectrogram draws). Returns
/// `false`, leaving `mags` untouched, if the size is unsupported or `mags` has
/// the wrong length. Zero-allocation: the transform runs in a stack buffer.
pub fn rfft_magnitudes_into(input: &[f32], mags: &mut [f32]) -> bool {
    let n = input.len();
    if mags.len() != n / 2 {
        return false;
    }
    macro_rules! arm {
        ($size:literal, $f:path) => {{
            let mut buf = [0.0f32; $size];
            buf.copy_from_slice(input);
            let spec = $f(&mut buf);
            // spec[0] packs (DC, Nyquist) in (re, im); the rest are ordinary
            // bins. We expose the DC magnitude and bins 1..n/2.
            mags[0] = spec[0].re.abs();
            for b in 1..$size / 2 {
                mags[b] = (spec[b].re * spec[b].re + spec[b].im * spec[b].im).sqrt();
            }
            true
        }};
    }
    match n {
        256 => arm!(256, real::rfft_256),
        512 => arm!(512, real::rfft_512),
        1024 => arm!(1024, real::rfft_1024),
        2048 => arm!(2048, real::rfft_2048),
        4096 => arm!(4096, real::rfft_4096),
        _ => false,
    }
}

/// Forward real FFT of `input` into the packed complex `frame`.
///
/// `input.len()` must be a [supported](SUPPORTED_SIZES) power of two `n` and
/// `frame.len()` must be `n`. On success `frame` holds the half-spectrum in the
/// canonical spectral-buffer layout -- the same one scsynth's `FFT` buffer uses:
///
/// ```text
/// frame = [ DC, Nyquist, re1, im1, re2, im2, ..., re_{n/2-1}, im_{n/2-1} ]
/// ```
///
/// The two purely-real terms (DC and Nyquist) share the first two slots; bins
/// `1..n/2` follow as interleaved real/imaginary pairs. Returns `false`,
/// leaving `frame` untouched, on a size mismatch. Zero-allocation.
pub fn rfft_into(input: &[f32], frame: &mut [f32]) -> bool {
    let n = input.len();
    if frame.len() != n {
        return false;
    }
    macro_rules! arm {
        ($size:literal, $f:path) => {{
            let mut buf = [0.0f32; $size];
            buf.copy_from_slice(input);
            let spec = $f(&mut buf);
            // spec[0] packs (DC, Nyquist) in (re, im); spec[1..n/2] are bins.
            frame[0] = spec[0].re;
            frame[1] = spec[0].im;
            for b in 1..$size / 2 {
                frame[2 * b] = spec[b].re;
                frame[2 * b + 1] = spec[b].im;
            }
            true
        }};
    }
    match n {
        256 => arm!(256, real::rfft_256),
        512 => arm!(512, real::rfft_512),
        1024 => arm!(1024, real::rfft_1024),
        2048 => arm!(2048, real::rfft_2048),
        4096 => arm!(4096, real::rfft_4096),
        _ => false,
    }
}

/// Inverse of [`rfft_into`]: the packed complex `frame` back to a real time
/// frame in `output`.
///
/// `output.len()` must be a [supported](SUPPORTED_SIZES) power of two `n` and
/// `frame.len()` must be `n` (the [`rfft_into`] layout). Returns `false` on a
/// size mismatch. Zero-allocation: the half-size spectrum is a stack buffer.
///
/// The spectrum `X` of a real frame is `E[k] + W^k O[k]`, with `E`, `O` the
/// `n/2`-point spectra of its even and odd samples and `W = e^{-j 2 pi / n}`;
/// with `X[n/2 - k]*` = `E[k] - W^k O[k]`, the two separate as
/// `E = (X[k] + X[n/2-k]*) / 2` and `O = (X[k] - X[n/2-k]*) / 2 * W^-k`. The
/// `n/2`-point inverse of `E + jO` is then `even + j odd`, both real --
/// `microfft::inverse` scales by `1/(n/2)`, the even and odd samples' own
/// transform length, so they come out at their level.
pub fn irfft_into(frame: &[f32], output: &mut [f32]) -> bool {
    let n = output.len();
    if frame.len() != n {
        return false;
    }
    // Bin `k` of the half-frame, `0..=n/2` (DC and Nyquist are real).
    let bin = |k: usize| -> Complex32 {
        if k == 0 {
            Complex32::new(frame[0], 0.0)
        } else if k == n / 2 {
            Complex32::new(frame[1], 0.0)
        } else {
            Complex32::new(frame[2 * k], frame[2 * k + 1])
        }
    };
    macro_rules! arm {
        ($half:literal, $f:path) => {{
            let stride = TWIDDLE_N / (2 * $half);
            let mut z = [Complex32::new(0.0, 0.0); $half];
            for (k, zk) in z.iter_mut().enumerate() {
                let (a, b) = (bin(k), bin($half - k).conj());
                let even = (a + b) * 0.5;
                let w = Complex32::new(twiddle::COS[k * stride], twiddle::SIN[k * stride]);
                let odd = (a - b) * 0.5 * w;
                *zk = even + Complex32::new(-odd.im, odd.re);
            }
            let time = $f(&mut z);
            for (pair, c) in output.chunks_exact_mut(2).zip(time.iter()) {
                pair[0] = c.re;
                pair[1] = c.im;
            }
            true
        }};
    }
    match n {
        256 => arm!(128, inverse::ifft_128),
        512 => arm!(256, inverse::ifft_256),
        1024 => arm!(512, inverse::ifft_512),
        2048 => arm!(1024, inverse::ifft_1024),
        4096 => arm!(2048, inverse::ifft_2048),
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::f32::consts::PI;

    #[test]
    fn impulse_is_a_flat_spectrum() {
        // FFT of a unit impulse is all-ones magnitude.
        let mut input = [0.0f32; 256];
        input[0] = 1.0;
        let mut mags = [0.0f32; 128];
        assert!(rfft_magnitudes_into(&input, &mut mags));
        for &m in &mags {
            assert!((m - 1.0).abs() < 1e-4, "flat spectrum, got {m}");
        }
    }

    #[test]
    fn cosine_peaks_at_its_bin() {
        let n = 1024usize;
        let k0 = 40usize;
        let input: Vec<f32> = (0..n)
            .map(|i| (2.0 * PI * k0 as f32 * i as f32 / n as f32).cos())
            .collect();
        let mut mags = vec![0.0f32; n / 2];
        assert!(rfft_magnitudes_into(&input, &mut mags));
        let peak = (0..n / 2)
            .max_by(|&a, &b| mags[a].partial_cmp(&mags[b]).unwrap())
            .unwrap();
        assert_eq!(peak, k0, "energy concentrates in the cosine's bin");
    }

    #[test]
    fn forward_inverse_round_trip_reconstructs_the_signal() {
        // A windowed real frame survives rfft_into -> irfft_into intact (no
        // overlap-add: a single frame reconstructs exactly up to FFT rounding).
        let n = 512usize;
        let signal: Vec<f32> = (0..n)
            .map(|i| {
                let x = i as f32 / n as f32;
                0.6 * (2.0 * PI * 5.0 * x).sin() + 0.3 * (2.0 * PI * 17.0 * x).cos()
            })
            .collect();
        let mut frame = vec![0.0f32; n];
        assert!(rfft_into(&signal, &mut frame));
        let mut back = vec![0.0f32; n];
        assert!(irfft_into(&frame, &mut back));
        for (a, b) in signal.iter().zip(back.iter()) {
            assert!((a - b).abs() < 1e-3, "round-trip {a} vs {b}");
        }
    }

    /// The inverse the half-size one replaced: rebuild the full Hermitian
    /// spectrum and run an `n`-point complex inverse. The reference the fast
    /// path is held to.
    fn irfft_full(frame: &[f32]) -> Vec<f32> {
        let n = frame.len();
        let mut spec = vec![Complex32::new(0.0, 0.0); n];
        spec[0] = Complex32::new(frame[0], 0.0);
        spec[n / 2] = Complex32::new(frame[1], 0.0);
        for b in 1..n / 2 {
            let c = Complex32::new(frame[2 * b], frame[2 * b + 1]);
            spec[b] = c;
            spec[n - b] = c.conj();
        }
        // The textbook sum in f64: slow, and exact to the last bit that
        // matters here.
        (0..n)
            .map(|t| {
                let mut acc = 0.0f64;
                for (k, c) in spec.iter().enumerate() {
                    let ph = 2.0 * std::f64::consts::PI * (k * t % n) as f64 / n as f64;
                    acc += c.re as f64 * ph.cos() - c.im as f64 * ph.sin();
                }
                (acc / n as f64) as f32
            })
            .collect()
    }

    /// The half-size inverse is the inverse DFT, to f32 rounding, at every
    /// supported size, on arbitrary spectra (not only ones a real frame
    /// produced).
    #[test]
    fn the_inverse_is_the_inverse_dft() {
        let mut state = 0x2545_f491_u32;
        let mut next = || {
            state ^= state << 13;
            state ^= state >> 17;
            state ^= state << 5;
            (state >> 8) as f32 / (1 << 23) as f32 - 1.0
        };
        for &n in SUPPORTED_SIZES {
            let frame: Vec<f32> = (0..n).map(|_| next() * 10.0).collect();
            let want = irfft_full(&frame);
            let mut got = vec![0.0f32; n];
            assert!(irfft_into(&frame, &mut got));
            let scale = want.iter().fold(0.0f32, |m, x| m.max(x.abs()));
            let err = got
                .iter()
                .zip(&want)
                .fold(0.0f32, |m, (a, b)| m.max((a - b).abs()));
            assert!(err < 1e-5 * scale, "n {n}: error {err} of {scale}");
        }
    }

    /// Forward then inverse is the identity to f32 rounding at every size.
    #[test]
    fn round_trip_is_exact_at_every_size() {
        for &n in SUPPORTED_SIZES {
            let signal: Vec<f32> = (0..n)
                .map(|i| ((i * 7919) % 97) as f32 / 48.0 - 1.0)
                .collect();
            let mut frame = vec![0.0f32; n];
            assert!(rfft_into(&signal, &mut frame));
            let mut back = vec![0.0f32; n];
            assert!(irfft_into(&frame, &mut back));
            for (i, (a, b)) in signal.iter().zip(&back).enumerate() {
                assert!((a - b).abs() < 2e-6, "n {n} at {i}: {a} vs {b}");
            }
        }
    }

    #[test]
    fn packed_dc_and_nyquist_match_the_definition() {
        // DC = sum of samples; Nyquist = alternating-sign sum. Packed in slots
        // 0 and 1 of the frame.
        let n = 256usize;
        let signal: Vec<f32> = (0..n).map(|i| (i % 4) as f32 - 1.5).collect();
        let mut frame = vec![0.0f32; n];
        assert!(rfft_into(&signal, &mut frame));
        let dc: f32 = signal.iter().sum();
        let nyq: f32 = signal
            .iter()
            .enumerate()
            .map(|(i, &s)| if i % 2 == 0 { s } else { -s })
            .sum();
        assert!((frame[0] - dc).abs() < 1e-2, "DC {} vs {dc}", frame[0]);
        assert!(
            (frame[1] - nyq).abs() < 1e-2,
            "Nyquist {} vs {nyq}",
            frame[1]
        );
    }

    #[test]
    fn rejects_unsupported_size_or_bad_output_length() {
        // Not a supported power of two.
        let input = [0.0f32; 100];
        let mut mags = [0.0f32; 50];
        assert!(!rfft_magnitudes_into(&input, &mut mags));
        // Right size, wrong output length.
        let input = [0.0f32; 256];
        let mut wrong = [0.0f32; 100];
        assert!(!rfft_magnitudes_into(&input, &mut wrong));
        assert!(supports(1024) && !supports(1000));
    }
}
