// Ephemeral defs: turning a bare expression into a sendable def (mirrors
// `clausters/defs/asdef.py`).
//
// The ambient verbs (`play`, `plot`, `render`) accept a bare expression — a
// UGen graph, a `ChannelList`, a Faust `Signal` — where a def is needed;
// `asDef` is the one coercion they share, so what is coercible is decided here
// and nowhere else. A `Ugen` expression is wrapped in `out(0.0, expr)` unless
// it already is a **sink**; a `ChannelList` lays its non-sink members on
// consecutive buses; a Faust `Signal` needs no wrapping, its outputs mapping
// to buses on their own. Names are autogenerated unless given, so each
// coercion is its own def.
//
// `exprChannels` answers the other half: how many buses the coercion would
// lay. The verbs read it differently on purpose — see its doc comment.
//
// **One kind the reference client coerces and this one cannot**: a Faust
// `Box`. The box algebra has no TypeScript surface yet (it is its own
// milestone), so there is nothing here to accept; `FaustDef.fromBox` takes the
// raw box JSON a generator emits, which is a def already.

import { FaustDef } from "./faustdef.ts";
import { GraphDef } from "./graphdef.ts";
import { Signal } from "./signals.ts";
import { SynthDef } from "./synthdef.ts";
import { ChannelList, Ugen, out } from "./ugens/index.ts";

/** Anything the ambient verbs accept where a def is expected. */
export type Expr = Ugen | ChannelList | Signal;

/**
 * UGen kinds that **deliver data out of the graph**: audio or control to a
 * bus, audio to a file, OSC or console text to a client. An expression rooted
 * in one of these is already where it is going, so `asDef` does not wrap it.
 *
 * The criterion is delivery, *not* "has a side effect". `freeSelf`,
 * `pauseSelf`, `freeSelfWhenDone` and `done` manage the enclosing synth and
 * pass their input through, so wrapping them is exactly right —
 * `out(0, freeSelfWhenDone(env.mul(sig)))` is the idiom. `detectSilence`
 * writes 0/1 for the rest of the graph, which is inward. `diskOut` *is* a
 * sink: it delivers audio to a file. It passes its input through too, but the
 * criterion is applied without an exception, so `play(diskOut(p, sig))`
 * records without sounding.
 */
const SINK_KINDS = new Set([
    "Out", "ReplaceOut", "OutCtl", "LocalOut", "DiskOut",
    "SendTrig", "SendReply", "Poll",
]);

/**
 * Prefix marking a def as **ephemeral** — the server keeps it in memory and
 * never writes it to its persistent store. The def family is part of the name
 * so two coercions of different families can never collide.
 */
const TMP_PREFIX = "tmp_";

/**
 * A name for a def nobody named: `tmp_<family>_<id>`.
 *
 * Unique across runs (a per-process counter would reuse the names of an
 * earlier session against a server that persists what it receives), distinct
 * per family, and marked ephemeral so the server never persists it at all.
 */
function tmpName(family: string): string {
    const id = Array.from({ length: 3 }, () =>
        Math.floor(Math.random() * 0x10000).toString(16).padStart(4, "0")).join("");
    return `${TMP_PREFIX}${family}_${id}`;
}

/** Whether `value` already delivers its data somewhere — see `SINK_KINDS`. */
function isSink(value: unknown): value is Ugen {
    return value instanceof Ugen && SINK_KINDS.has(value.kind);
}

/** Whether `value` is a bare expression the verbs can coerce into a def. */
export function isExpr(value: unknown): value is Expr {
    return value instanceof Ugen || value instanceof ChannelList
        || value instanceof Signal;
}

/**
 * Coerces `expr` into a def, autonaming it unless `name` is given.
 *
 * A `SynthDef`/`FaustDef`/`GraphDef` passes through unchanged (`name` is
 * ignored). A `Ugen` becomes a `SynthDef`, wrapped in `out(0.0, expr)` unless
 * it already is a sink. A `ChannelList` becomes a multichannel `SynthDef`: a
 * member that is a sink already knows where its data goes and passes through
 * as a root, and the members that are not are the channels, laid on
 * consecutive buses from 0 — so `play(dup(expr))` is stereo, and a reporter in
 * the list does not push the audio off bus 0. A `Signal` becomes a one-output
 * `FaustDef`.
 */
export function asDef(
    expr: Expr | SynthDef | FaustDef | GraphDef,
    name?: string,
): SynthDef | FaustDef | GraphDef {
    if (expr instanceof SynthDef || expr instanceof FaustDef || expr instanceof GraphDef) {
        return expr;
    }
    if (expr instanceof Ugen) {
        return new SynthDef(
            name ?? tmpName("synthdef"),
            isSink(expr) ? expr : out(0.0, expr),
        );
    }
    if (expr instanceof ChannelList) {
        let bus = 0;
        const roots = [...expr].map((member) =>
            isSink(member) ? member : out(bus++, member));
        return new SynthDef(name ?? tmpName("synthdef"), ...roots);
    }
    if (expr instanceof Signal) {
        return FaustDef.fromSignals(name ?? tmpName("faustdef"), expr);
    }
    throw new TypeError(
        "cannot make a def out of this; expected a Ugen, a ChannelList, a Signal, "
            + "or a def (SynthDef/FaustDef/GraphDef). A Control is a graph leaf, not "
            + "an expression to play on its own: use it inside one.",
    );
}

/**
 * How many buses `asDef` would lay `expr` on, or `null` when that is not
 * knowable (an already-built def routes its own roots, possibly to computed
 * buses).
 *
 * The verbs read this differently, and the difference is deliberate. `plot`
 * and `play` are conveniences, free to infer what was meant: `plot`
 * **configures** its render from this, so a stereo pair plots as two channels.
 * `render` is part of the offline interface — its `channels` is the render's
 * *output* count, a fact about the server being configured, not about the
 * graph — so it derives nothing and only **checks**.
 *
 * A sink lays no bus of `asDef`'s choosing, so an expression made only of
 * sinks answers `0`: it routes itself, and there is nothing here to infer.
 */
export function exprChannels(expr: unknown): number | null {
    if (expr instanceof ChannelList) {
        return [...expr].filter((member) => !isSink(member)).length;
    }
    if (expr instanceof Ugen) return isSink(expr) ? 0 : 1;
    if (expr instanceof Signal) return 1;
    return null;
}
