//! Buffer readers, buffer info, and the table oscillators.
//!
//! One slice of the catalog, in its place in the table order;
//! `super::FAMILIES` concatenates them all.

use super::*;

pub(super) static UGENS: &[UGenDescriptor] = &[
    // --- buffer readers and info ---
    desc_done(desc(
        "PlayBuf",
        Fixed(7),
        &[
            inp("bufnum", 0.0),
            inp("chan", 0.0),
            inp("rate", 1.0),
            inp("loop", 0.0),
            inp("trigger", 0.0),
            inp("start_pos", 0.0),
            inp("done_action", 0.0),
        ],
        Ar,
        R_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(PlayBuf::new()),
    )),
    desc(
        "BufRd",
        Fixed(4),
        &[
            inp("bufnum", 0.0),
            inp("chan", 0.0),
            inp("phase", 0.0),
            inp("loop", 0.0),
        ],
        Ar,
        R_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(BufRd),
    ),
    // --- buffer writers; a buffer's contents are mutable (`dsp::buffer`) ---
    desc(
        "BufWr",
        Fixed(5),
        &[
            inp("bufnum", 0.0),
            inp("chan", 0.0),
            inp("phase", 0.0),
            inp("loop", 0.0),
            inp("signal", 0.0),
        ],
        Ar,
        R_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(BufWr),
    ),
    desc_done(desc(
        "RecordBuf",
        Fixed(10),
        &[
            inp("bufnum", 0.0),
            inp("chan", 0.0),
            inp("signal", 0.0),
            inp("offset", 0.0),
            inp("rec_level", 1.0),
            inp("pre_level", 0.0),
            inp("run", 1.0),
            inp("loop", 0.0),
            inp("trigger", 0.0),
            inp("done_action", 0.0),
        ],
        Ar,
        R_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(RecordBuf::new()),
    )),
    // --- table oscillators & waveshaper; read `/buffer_gen` wavetables ---
    desc(
        "Osc",
        Fixed(3),
        I_TABLE_OSC,
        Ar,
        R_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Osc::new()),
    ),
    desc(
        "OscN",
        Fixed(3),
        I_TABLE_OSC,
        Ar,
        R_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(OscN::new()),
    ),
    desc(
        "VOsc",
        Fixed(3),
        &[inp("bufpos", 0.0), inp("freq", 440.0), inp("phase", 0.0)],
        Ar,
        R_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(VOsc::new()),
    ),
    desc(
        "Shaper",
        Fixed(2),
        &[inp("bufnum", 0.0), inp("signal", 0.0)],
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Shaper),
    ),
    desc(
        "BufSampleRate",
        Fixed(1),
        I_BUFNUM,
        Ar,
        R_IR_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(BufInfo(BufInfoKind::SampleRate)),
    ),
    desc(
        "BufRateScale",
        Fixed(1),
        I_BUFNUM,
        Ar,
        R_IR_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(BufInfo(BufInfoKind::RateScale)),
    ),
    desc(
        "BufFrames",
        Fixed(1),
        I_BUFNUM,
        Ar,
        R_IR_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(BufInfo(BufInfoKind::Frames)),
    ),
    desc(
        "BufChannels",
        Fixed(1),
        I_BUFNUM,
        Ar,
        R_IR_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(BufInfo(BufInfoKind::Channels)),
    ),
    desc(
        "BufDur",
        Fixed(1),
        I_BUFNUM,
        Ar,
        R_IR_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(BufInfo(BufInfoKind::Duration)),
    ),
];
