//! Demand rate: the substrate and its drivers.
//!
//! One slice of the catalog, in its place in the table order;
//! `super::FAMILIES` concatenates them all.

use super::*;

pub(super) static UGENS: &[UGenDescriptor] = &[
    // --- demand rate (substrate): a driver runs specially and
    //     pulls; a source is skipped in block order and reached only through a
    //     pull, its own inputs pulled with it when they are streams too. ---
    desc(
        "Demand",
        Fixed(3),
        &[inp("trig", 0.0), inp("reset", 0.0), inp("source", 0.0)],
        Ar,
        R_KR_AR,
        DemandDriver,
        BusRole::None,
        false,
        |_, _| Box::new(Demand::new()),
    ),
    desc_done(desc(
        "Duty",
        Fixed(4),
        I_DUTY,
        Ar,
        R_KR_AR,
        DemandDriver,
        BusRole::None,
        false,
        |_, _| Box::new(Duty::new(DutyKind::Hold)),
    )),
    desc_done(desc(
        "TDuty",
        Fixed(5),
        I_TDUTY,
        Ar,
        R_KR_AR,
        DemandDriver,
        BusRole::None,
        false,
        |_, _| Box::new(Duty::new(DutyKind::Trigger)),
    )),
    desc(
        "Dseq",
        Variadic,
        I_REPEATS,
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Dlist::with_seed(ListOrder::Seq, ctx.next_seed())),
    ),
    desc(
        "Drand",
        Variadic,
        I_REPEATS,
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Dlist::with_seed(ListOrder::Rand, ctx.next_seed())),
    ),
    desc(
        "Dxrand",
        Variadic,
        I_REPEATS,
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Dlist::with_seed(ListOrder::Xrand, ctx.next_seed())),
    ),
    desc(
        "Dshuf",
        Variadic,
        I_REPEATS,
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Dlist::with_seed(ListOrder::Shuf, ctx.next_seed())),
    ),
    desc(
        "Dseries",
        Fixed(3),
        &[inp("repeats", 0.0), inp("start", 0.0), inp("step", 1.0)],
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Dramp::new(RampKind::Series)),
    ),
    desc(
        "Dgeom",
        Fixed(3),
        &[inp("repeats", 0.0), inp("start", 1.0), inp("grow", 2.0)],
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Dramp::new(RampKind::Geom)),
    ),
    desc(
        "Dwhite",
        Fixed(3),
        I_DRAW,
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Drandom::with_seed(RandKind::White, ctx.next_seed())),
    ),
    desc(
        "Diwhite",
        Fixed(3),
        I_DRAW,
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Drandom::with_seed(RandKind::IWhite, ctx.next_seed())),
    ),
    desc(
        "Dbrown",
        Fixed(4),
        I_DWALK,
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Drandom::with_seed(RandKind::Brown, ctx.next_seed())),
    ),
    desc(
        "Dibrown",
        Fixed(4),
        // Same shape as `I_DWALK`, but a walk over the integers whose default
        // step was a hundredth would never move.
        &[
            inp("repeats", 0.0),
            inp("lo", 0.0),
            inp("hi", 1.0),
            inp("step", 1.0),
        ],
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Drandom::with_seed(RandKind::IBrown, ctx.next_seed())),
    ),
    desc(
        "Dstutter",
        Fixed(2),
        &[inp("repeats", 1.0), inp("value", 0.0)],
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Dstutter::new()),
    ),
    desc(
        "Dswitch1",
        Variadic,
        I_WHICH,
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Dswitch1),
    ),
    desc(
        "Dbufrd",
        Fixed(4),
        &[
            inp("bufnum", 0.0),
            inp("phase", 0.0),
            inp_opt("loop", 1.0),
            inp_opt("channel", 0.0),
        ],
        Dr,
        R_DR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Dbufrd),
    ),
];
