//! The filter core: one state-variable topology behind every name.
//!
//! One slice of the catalog, in its place in the table order;
//! `super::FAMILIES` concatenates them all.

use super::*;

pub(super) static UGENS: &[UGenDescriptor] = &[
    // --- the filter core: one topology-preserving state-variable
    //     implementation behind every two-pole name, plus the one-pole family.
    //     `BPF` and `Resonz` are the same row twice on purpose - scsynth ships
    //     two historically distinct resonators with the same parameterization
    //     and the same unity peak gain. See `dsp::filter`. ---
    desc(
        "LPF",
        Fixed(2),
        I_FILT,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Svf::new(SvfMode::Lp)),
    ),
    desc(
        "HPF",
        Fixed(2),
        I_FILT,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Svf::new(SvfMode::Hp)),
    ),
    desc(
        "RLPF",
        Fixed(3),
        I_FILT_RQ,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Svf::new(SvfMode::RLp)),
    ),
    desc(
        "RHPF",
        Fixed(3),
        I_FILT_RQ,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Svf::new(SvfMode::RHp)),
    ),
    desc(
        "BPF",
        Fixed(3),
        I_FILT_RQ,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Svf::new(SvfMode::Bp)),
    ),
    desc(
        "Resonz",
        Fixed(3),
        I_FILT_RQ,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Svf::new(SvfMode::Bp)),
    ),
    desc(
        "BRF",
        Fixed(3),
        I_FILT_RQ,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Svf::new(SvfMode::Notch)),
    ),
    desc(
        "Svf",
        Fixed(6),
        &[
            inp("signal", 0.0),
            inp("freq", 440.0),
            inp("rq", 1.0),
            inp("low", 1.0),
            inp("band", 0.0),
            inp("high", 0.0),
        ],
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Svf::new(SvfMode::Mix)),
    ),
    desc(
        "OnePole",
        Fixed(2),
        I_ONE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(OneFilter::new(OneKind::OnePole)),
    ),
    desc(
        "OneZero",
        Fixed(2),
        I_ONE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(OneFilter::new(OneKind::OneZero)),
    ),
    desc(
        "LeakDC",
        Fixed(2),
        I_LEAK,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(OneFilter::new(OneKind::LeakDc)),
    ),
    desc(
        "Integrator",
        Fixed(2),
        I_INTEGRATE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(OneFilter::new(OneKind::Integrator)),
    ),
];
