//! Noise, by spectrum and by density.
//!
//! One slice of the catalog, in its place in the table order;
//! `super::FAMILIES` concatenates them all.

use super::*;

pub(super) static UGENS: &[UGenDescriptor] = &[
    // --- noise ---
    desc(
        "PinkNoise",
        Fixed(0),
        I_NONE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(PinkNoise::with_seed(ctx.next_seed())),
    ),
    desc(
        "BrownNoise",
        Fixed(0),
        I_NONE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(BrownNoise::with_seed(ctx.next_seed())),
    ),
    desc(
        "GrayNoise",
        Fixed(0),
        I_NONE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(GrayNoise::with_seed(ctx.next_seed())),
    ),
    desc(
        "ClipNoise",
        Fixed(0),
        I_NONE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(ClipNoise::with_seed(ctx.next_seed())),
    ),
    desc(
        "LFNoise0",
        Fixed(1),
        I_LF_NOISE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(LfNoise::with_seed(LfNoiseShape::Step, ctx.next_seed())),
    ),
    desc(
        "LFNoise1",
        Fixed(1),
        I_LF_NOISE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(LfNoise::with_seed(LfNoiseShape::Linear, ctx.next_seed())),
    ),
    desc(
        "LFNoise2",
        Fixed(1),
        I_LF_NOISE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(LfNoise::with_seed(LfNoiseShape::Quadratic, ctx.next_seed())),
    ),
    desc(
        "LFClipNoise",
        Fixed(1),
        I_LF_NOISE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(LfNoise::with_seed(LfNoiseShape::Clip, ctx.next_seed())),
    ),
    desc(
        "Dust",
        Fixed(1),
        I_DENSITY,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Dust::with_seed(DustMode::Unipolar, ctx.next_seed())),
    ),
    desc(
        "Dust2",
        Fixed(1),
        I_DENSITY,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, ctx| Box::new(Dust::with_seed(DustMode::Bipolar, ctx.next_seed())),
    ),
    desc(
        "Crackle",
        Fixed(1),
        I_CHAOS,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Crackle::default()),
    ),
];
