//! Panning, the stereo field and selection.
//!
//! One slice of the catalog, in its place in the table order;
//! `super::FAMILIES` concatenates them all.

use super::*;

pub(super) static UGENS: &[UGenDescriptor] = &[
    // --- panning, the stereo field and selection: one pan law, one
    //     two-by-two matrix, one crossfade. The two-channel rows appear once
    //     each and carry a `chan` index; `numchans` on `PanAz` sizes the ring
    //     the gain is computed against, not an allocation. ---
    desc(
        "Pan2",
        Fixed(4),
        I_PAN2,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Pan::new(PanKind::Pan2)),
    ),
    desc(
        "LinPan2",
        Fixed(4),
        I_PAN2,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Pan::new(PanKind::LinPan2)),
    ),
    desc(
        "Balance2",
        Fixed(5),
        I_BALANCE2,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Pan::new(PanKind::Balance2)),
    ),
    desc(
        "XFade2",
        Fixed(4),
        I_XFADE2,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Pan::new(PanKind::XFade2)),
    ),
    desc(
        "LinXFade2",
        Fixed(4),
        I_XFADE2,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Pan::new(PanKind::LinXFade2)),
    ),
    desc(
        "Rotate2",
        Fixed(4),
        I_ROTATE2,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Rotate::new(RotKind::Rotate2)),
    ),
    desc(
        "MidSide",
        Fixed(3),
        I_MIDSIDE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Rotate::new(RotKind::MidSide)),
    ),
    desc(
        "StereoWidth",
        Fixed(4),
        I_WIDTH,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Rotate::new(RotKind::Width)),
    ),
    desc(
        "PanAz",
        Fixed(7),
        I_PAN_AZ,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(PanAz),
    ),
    desc(
        "Select",
        Variadic,
        I_WHICH,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Select::new(SelectKind::Pick)),
    ),
    desc(
        "SelectX",
        Variadic,
        I_WHICH,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Select::new(SelectKind::Cross)),
    ),
];
