//! Triggers, node control and the init-rate scalars.
//!
//! One slice of the catalog, in its place in the table order;
//! `super::FAMILIES` concatenates them all.

use super::*;

pub(super) static UGENS: &[UGenDescriptor] = &[
    // --- triggers and control ---
    // All of these default to `ar`, counters included. A `kr` UGen reads one
    // sample per block from an `ar` input, so a `kr` counter fed an `ar`
    // trigger train would silently miss 63 triggers out of 64; the cheaper
    // pairing has to be asked for, and asked for on both ends.
    desc(
        "Trig",
        Fixed(2),
        I_TRIG_DUR,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(TrigPulse::new(TrigMode::Level)),
    ),
    desc(
        "Trig1",
        Fixed(2),
        I_TRIG_DUR,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(TrigPulse::new(TrigMode::Unit)),
    ),
    desc(
        "TDelay",
        Fixed(2),
        I_TRIG_DUR,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(TrigPulse::new(TrigMode::Delay)),
    ),
    desc(
        "Latch",
        Fixed(2),
        I_HOLD,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Hold::new(HoldMode::Latch)),
    ),
    desc(
        "Gate",
        Fixed(2),
        I_HOLD,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Hold::new(HoldMode::Gate)),
    ),
    desc(
        "Schmidt",
        Fixed(3),
        I_SCHMIDT,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Schmidt::default()),
    ),
    desc(
        "ToggleFF",
        Fixed(1),
        I_TRIG,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(FlipFlop::new(FlipFlopMode::Toggle)),
    ),
    desc(
        "SetResetFF",
        Fixed(2),
        I_TRIG_RESET,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(FlipFlop::new(FlipFlopMode::SetReset)),
    ),
    desc(
        "PulseCount",
        Fixed(2),
        I_TRIG_RESET,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Counter::new(CounterMode::Count)),
    ),
    desc(
        "PulseDivider",
        Fixed(3),
        I_DIVIDER,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Counter::new(CounterMode::Divide)),
    ),
    desc(
        "Stepper",
        Fixed(6),
        I_STEPPER,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Stepper::default()),
    ),
    desc(
        "Timer",
        Fixed(1),
        I_TRIG,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Elapsed::new(ElapsedMode::Timer)),
    ),
    desc(
        "Sweep",
        Fixed(2),
        I_SWEEP,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Elapsed::new(ElapsedMode::Sweep)),
    ),
    desc(
        "Changed",
        Fixed(2),
        I_CHANGED,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Changed::default()),
    ),
    desc(
        "Decay",
        Fixed(2),
        I_DECAY,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Decay::new(false)),
    ),
    desc(
        "Decay2",
        Fixed(3),
        I_DECAY2,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Decay::new(true)),
    ),
    // The one row here with a done flag: it exists to notice that a voice has
    // nothing left to say, so `Done`/`FreeSelfWhenDone` can watch it too.
    desc_done(desc(
        "DetectSilence",
        Fixed(4),
        I_SILENCE,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(DetectSilence::default()),
    )),
    // --- node control ---
    // These four pass their input through and act on their own node. The first
    // two read a signal; the last two read another UGen's done flag, which is
    // why they run in `DoneQuery` rather than `Normal`.
    desc(
        "FreeSelf",
        Fixed(1),
        I_SIGNAL,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(SelfControl::new(DoneAction::FreeSelf)),
    ),
    desc(
        "PauseSelf",
        Fixed(1),
        I_SIGNAL,
        Ar,
        R_KR_AR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(SelfControl::new(DoneAction::PauseSelf)),
    ),
    desc(
        "Done",
        Fixed(1),
        I_SOURCE,
        Ar,
        R_KR_AR,
        DoneQuery,
        BusRole::None,
        false,
        |_, _| Box::new(WhenDone::new(WhenDoneMode::Report)),
    ),
    desc(
        "FreeSelfWhenDone",
        Fixed(1),
        I_SOURCE,
        Ar,
        R_KR_AR,
        DoneQuery,
        BusRole::None,
        false,
        |_, _| Box::new(WhenDone::new(WhenDoneMode::Free)),
    ),
    // --- scalar / init-rate ---
    desc(
        "SampleRate",
        Fixed(0),
        I_NONE,
        Ir,
        R_IR_KR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(SampleRate),
    ),
    desc(
        "Rand",
        Fixed(2),
        &[inp("lo", 0.0), inp("hi", 1.0)],
        Ir,
        R_IR,
        Normal,
        BusRole::None,
        false,
        |_, _| Box::new(Rand::new()),
    ),
];
